jameshughes89/cs102

README.md
=> fix setup script in readme, add some fancy formating

.github/workflows/sphinx-build.yml, .gitignore
because I'm a bro
:tito:
example run: https://github.com/twentylemon/cs102/actions/runs/899992811
doesn't seem to be running for your repo yet -- you may have to enable them for pull requests in the repo settings
=> add basic sphinx build action

source/conf.py
Added individual contributing significant editing to copyright of page.
=> Add dude putting in significant editing to copyright

source/topic4.rst
Topic 4 will re-set the tone and focus of the course after the Java v Python heavy stuff.
=> Topic4 adt

code/ContactList.java, source/topic3.rst
Added a method to get the size of the ContactList.
=> Add size method to ContactList

source/topic1.rst, source/topic10.rst, source/topic11.rst, source/topic12.rst, source/topic13.rst, source/topic14.rst, source/topic15.rst, source/topic16.rst, source/topic17.rst, source/topic18.rst, source/topic19.rst, source/topic2.rst, source/topic20.rst, source/topic21.rst, source/topic22.rst, source/topic23.rst, source/topic24.rst, source/topic3.rst, source/topic4.rst, source/topic5.rst, source/topic6.rst, source/topic7.rst, source/topic8.rst, source/topic9.rst
Nothing really to review here. You'll just have to go with me on this and trust that the chapters are right.
=> Add chapters to read and put in number of pages to read

source/topic5.rst
Subsection on the stack specific operations.
=> Topic 5 Create subsection on stack operations

source/topic5-postfix.rst, source/topic5.rst
Move the postfix to an aside page for Topic5. Will keep it since it's in the text and I believe a common-ish example. Either way, more examples probably wont hurt.
=> Topic5 postfix example to an aside

source/topic4.rst
Fixes the broken turtle link, a small typo, and made \` into \`` to properly format code like stuff.
=> Topic4 Content fixes

source/topic6.rst
Highlight that we now go from _what_ to **how**. Think about implementation details.
=> Topic6 Introduction

.gitignore
=> Update gitignore for assignments to reflect changes in directories

src/site/topic7.rst
Change `_node_` to `*node*` because that's how it works.
=> Topic7 Typo fix

src/main/java/Node.java
The `Node.java` file. Information from the file will be used for Topic7.
Originally this was not going to contain the documentation, but I threw it in anyways.
=> Topic7 Node class

src/site/topic5.rst
Small spelling fix in Topic 5.
=> fixed typo out -> our

src/site/topic8.rst
Title. 
The review of Stack ADT was not a section before, but now is.
=> Topic8 Introduction and review of Stack ADT

src/main/java/LinkedStack.java, src/site/topic8.rst
Forgot to include `toString` for Topic8. 
It's ugly.
=> Topic8 toString

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
#81 
Adding "Related" to the first header in templates.
Looking at #85, just seemed off.
Rich diff viewer.
=> :lipstick: specify "related" for issues/prs in templates

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Closes #85 
Changing out the emojies to relate to the labels. Some labels were changed and removed from repo. 
This allows people contributing to self tag their PRs and Issues
=> :memo: Update and change emojies to correspond to labels

src/site/topic9.rst
Add a few examples of derriving `t(n)`. 
Topic9.rst
=> :mortar_board: Topic9 Add section showing examples of derriving t(n)

README.md
Related to #28 
Add a section for contributing that links to CONTRIBUTING.md.
This may make it more obvious to new people where to go to see how to contribute.
README.md
=> :memo: Add link to CONTRIBUTING to the README page

src/main/java/Queue.java
Add the `Queue` interface to the repo. This will be used for Topic10. 
New file in the repo called `Queue.java`
=> :new: :mortar_board: Topic10 Add the queue interface to the repo

src/site/topic10.rst
More or less copy #101 
Put the interface code into the topic10 page. 
Add download link for the Queue interface. 
Topic10.rst
=> :mortar_board: Topic10 Add Queue interface to the topic page

src/site/topic10.rst, src/site/topic6-testing.rst, src/site/topic7.rst, src/site/topic8-nested.rst, src/site/topic8.rst, src/site/topic9.rst
Update various images' sizes. 
Helps with the look of the images. Some were too small to read. Some were way inconsistent with other similar images. 
Specifically the following, but all pages up to and including 10 were checked. 
topic10.rst
topic6-testing.rst
topic7.rst
topic8-nested.rst
topic8.rst
topic9.rst
Checked how they looked locally.
=> :mortar_board: :lipstick: :art: :telescope: Change sizes of images

src/site/topic11.rst
Introduction section setting up for a linked implementation of a queue.
topic11.rst
=> :mortar_board::new: Topic11 Introduction section

src/site/topic8.rst
Fix typo in comment at the top of the playing code for `LinkedStack`.
It originally says `// Create an ArrayStack` when it should say `// Create a LinkedStack`.
topic8.rst
=> :bug: :mortar_board: Topic8 Typo in comment for playing code

src/site/topic11.rst
Add the section on enqueuing to the topic11 page. 
Two sub-sub-sections are made to go into a little more detail as sometimes this can throw them (usually because they're rusing). 
topic11.rst
=> :new: :mortar_board: Topic11 Section on enqueuing

src/main/java/LinkedQueue.java, src/test/java/LinkedQueueTest.java
Add `LinkedQueue` and `LinkedQueueTest` to the repo. 
src/main/java/LinkedQueue.java
src/test/java/LinkedQueueTest.java
Ran the tests locally.
=> :new: :mortar_board: Topic11 LinkedQueue implementation with LinkedQueueTest

src/site/topic11.rst
Subsection on a priority queue. No implementation, but a discussion on the _what_ and the _how_. 
Added download links to the `LinkedQueue` code and tests too. 
topic11.rst
=> :new: :mortar_board: Topic11 Section on priority queues

src/site/topic11.rst
Add section on dequeuing and first. Goes over some nuances of edge cases. 
topic11.rst
=> :new: :mortar_board: Topic11 Dequeueing and first section

src/main/java/ContactList.java, src/site/topic11.rst, src/site/topic3.rst
Closes #115 
Update the `if`/`else` to match 
```java
if (condition) {
...
} else {
...
}
```
More typical style. 
Only ended up being in:
topic11.rst
topic3.rst
ContactList.java
Just looked at the files.
Checked for extra with grep.
=> :telescope: :bug: Update `if`/`else` statements

src/site/topic11.rst
As per #77, this will be in a downloadable file one day.
Add simple playing and testing code for a `LinkedQueue`
topic11.rst
Tested the playing code locally
=> :new: :mortar_board: Topic11 Add playing code

src/main/java/ArrayQueue.java, src/test/java/ArrayQueueTest.java
Add the implementation and tests for `ArrayQueue`
src/main/java/ArrayQueue.java
src/test/java/ArrayQueueTest.java
Ran tests locally. 
Comments are a little dry. Perhaps add more?
=> :new: :mortar_board: Topic12 `ArrayQueue` and `ArrayQueueTest` code added to repo

src/site/topic12.rst
Short intro setting up the `ArrayQueue` implementation.
=> :new: :mortar_board: Topic12 Intro section

src/site/topic12.rst
Add a section covering the more nuanced methods from the `ArrayQueue`.
At this stage, the other methods _should_ be simple.
Will next add a section on testing to highlight the test that was worked on for `expandCapacity`.
=> :new: :mortar_board: Topic12 Add section on implementation

src/site/topic12.rst
Playing code dumped to the end of the topic page. 
Download links added for the `.java` files.
=> :new: :mortar_board: Topic12 Add playing code and download links to .java files

src/site/topic13.rst, src/site/topic14.rst
Related #138 #137 #136 
Reorder topics 13 & 14 such that interface inheritance is seen first. 
Inheritance will be discussed in topic13's page but the next topic will discuss it too with the emphasis being on polymorphism & binding. 
Deemphasize class inheritance and hit interface inheritance harder. 
Topic 13 & 14 but there willl likely be new asides. 
What topic14 actually turns into remains to be determined.
=> :new: :mortar_board: Topic13/14 Reorder topics

src/site/topic13.rst
Related-ish to #158 
Add intro to Bag topic (this is replacing the list stuff)
Bags make more sense in terms of the leraning objectives. 
Topic 13
I'm conflicted on if we can call a bag a _linear_ structure.
=> :mortar_board: Topic13 Bag topic introduction

src/main/java/Bag.java, src/site/topic13.rst
Add section to topic page on bag functionality. Also add download links for the various bag interfaces.
=> :mortar_board: Topic13 Section for bag functionality 

src/site/topic14.rst
Add a section for inheritance terminology.
=> :mortar_board: Topic14 Add Terminology section 

src/site/topic14.rst
Add a section on `Object`. This is brief as they would have been familiar with this passively when writing their `toString` and `equals`.
=> :mortar_board: Topic14 Object section

src/site/lab2.rst
Lab 2 focuses on Topic3 --- objects and collections of objects
Reinforces ideas they see in class. If they have a head on their shoulders, this should be a trivial lab since they can nearly copy/paste from topic3. 
This was week 4's lab back when using C++. Look how much we can shift the focus to the actual learning objectives of the course.
=> :mortar_board: Lab2 Playing with Objects

src/main/java/ArraySortedBag.java, src/site/topic15.rst
Finish the section on `ArraySortedBag`. The only thing added is the `add` and `findInsertIndex` since the other methods should be simple enough for them at this stage. Either way, they have download links to the rest of the methods. 
There is also a fix in the `ArraySortedBag.java` file. Was missed since it was a commented out version of a method. Also removed a commented out version of a method that was useless.
=> :mortar_board: Topic15 Finish section on `ArraySortedBag`

src/site/topic15.rst
The remaining points on the `ArrayIndexedList` class. The simpler methods are not discussed within the topic page.
=> :mortar_board: Topic15 Finish section on ``ArrayIndexedBag`` 

src/site/lab3.rst
Created and added Lab3 to course. This lab covers stacks and using it to reverse a string
=> :mortar_board: Lab3

src/main/java/ArraySortedBag.java, src/site/topic15.rst
Start the `ArraySortedBag` section. This PR mostly focuses on `Comparable` and `compareTo`.
=> :mortar_board: Topic15 Start section for ``ArraySortedBag``

src/site/topic15.rst
Depends on #180 & #181 
Add download links to the Topic15 page for the tests. 
As of when this PR was made, the links are dead since their PRs have not been merged.
=> :mortar_board: Topic15 Add download links for tests 

src/site/topic16.rst
Start the iterator introduction section. Also lays out the high level plan for the topic points to hit.
=> :mortar_board: Topic16 Iterators intro

src/site/lab3.rst
Adding a section on them testing their stack. 
Since the testing aside is brought up with `ArrayStack`, this seems as good of a time as any to have them do it. 
There are two points to this:
1. They figure out how to use JUnit
2. They learn about testing and thinking about the functionality more 
I would prefer to have a whole lab dedicated to testing, but at this stage, I put it here within this lab since the pace of the course is going to be radically different from the Cpp version and I do not know if the labs will keep up if we don't go from Classes -> `ArrayStack` -> Linked structures. 
When going through the content, if the pace seems right and we can squeeze in another lab before getting to the `ArrayStack`, I will make this Lab3 be Lab4 and have the Lab3 be writing tests for the …
=> :new: :mortar_board: Lab3 Add section on testing the stack

src/site/topic15.rst
Fix the order of the sections for Topic15. 
Add a short section saying to check out the tests on their own. 
Section order got messed up with merges. 
Tests are not directly discussed since they should be familiar with them by now, but still presented since all the test methods are far more comprehensive than previous.
=> :bug: :mortar_board: Topic15 Fix ordering of sections and add testing section

src/site/topic19.rst
Sections for tentitive topics. 
May cut Towers of Hanoi, but I do enjoy telling _the legend_ that goes with it to demonstrate that computational complexity and exponential growth are fun.
=> :mortar_board: Topic19 Sections

src/site/topic20.rst, src/site/topic21.rst, src/site/topic22.rst, src/site/topic23.rst
Related #199 discussion 
Reorder topics to introduce searching after recursion.
As @twentylemon suggests, the transition from the iterator aside on spliterator -> recursion -> seraching (linear & binary, both iterative and recursive) -> binary search trees, is a great idea. 
After recursion, before trees
Also lets us hit array binary serach and then the tree idea, which is cool.
=> :mortar_board: Reorder search topic

src/site/topic18.rst
Rename the section to be slightly broader.
Add sections for tentative plan.  
The stack overflow will show a recursive function that just pushes frames. This will nicely lead into recursion.
=> :mortar_board: Topic18 Rename topic and add sections

src/main/java/BinaryTree.java
Create a binary tree interface.
The current plan is:
1. `BinaryTree` interface
2. `BinarySearchTree` interface
3. `LinkedBinarySerachTree` implementation
4. Mayyyyyybe an `ArrayBinarySearchTree` implementation that ~basically a heap~ indexes left/right like a heap (this may end up being a lab, idk)
5. Use a `BinarySearchTree` to implement `SortedBag`
Though, this may change depending on how things fall into place.
=> :mortar_board: Binary tree interface

src/main/java/LinkedIterator.java
Add the `LinkedIterator` class for topic17.
They will need it. 
This one is tricky because:
1. They may or may not have made the `Node` class a static inner class --- that was an aside. Though, do note that I will be using it as an internal class. (In fact, this can be an interesting talking point about where to put it). 
2. I will make this a static nested class, but leave a seperate class here anyways in case we want/need it.
3. I suppose it could be a regular inner class for access to `head`, but idk, I like it as static since it will be closer to having it a seperate class.
=> :mortar_board: Topic17 `LinkedIterator` class

src/main/java/BinarySearchTree.java, src/main/java/SortedBag.java
Related-ish to #199 
Add the `BinarySearchTree` interface to the content. 
There may be more worthwile methods, but I can't think of any right now
=> :mortar_board: `BinarySearchTree` interface

src/main/java/BinarySearchTree.java, src/main/java/LinkedBinarySearchTree.java, src/test/java/LinkedBinarySearchTreeTest.java
Adding a linked implementation of a binary search tree.
For the course content. 
Tests written.
This PR is rather large. Sorry.
=> :mortar_board: `LinkedBinarySearchTree` implementation

src/site/topic16.rst
Small change to wording around `for` loops and linked structures.
You could totally use a for loop still for the linked structure, but not the same way as we would with the array.
=> :bug: :mortar_board: Topic16 Change wording around for loops and linked structures

src/site/topic16.rst
Add high level description of iterators to the topic. 
Note, at this stage they will have seen and used them. This topic is intended to fill in some gaps.
=> :mortar_board: Topic16 Add description of iterators and iterator interface

src/site/topic16.rst
Add a discussion on `ArrayIterator`
=> :mortar_board: Topic16 Array Iterator

src/site/topic16.rst
Discuss the `LinkedIterator` implementation. 
A warning is included about being an internal class.
=> :mortar_board: Topic16 Add discussion on `LinkedIterator`

.gitignore, src/site/topic16.rst
Add a few examples of using the iterators with our collections
1) Writing our iterator methods 
2) Getting an iterator from a `SortedBag`
3) Using an iterator for `toString()`
=> :mortar_board: Topic16 Examples of using the iterators

src/site/topic16.rst
Add two warnings (really, they're more notes I guess) about the _direction_ the iterator moves and the iterator messing with the thing it's iterating over.
=> :mortar_board: Add 'warnings' about direction and modifying

src/site/topic16.rst
Discuss the `Iterable` interface, implementing it, and using for each loops.
=> :mortar_board: Topic16 Add notes and examples for Iterable

src/site/topic16.rst
Add download links for the code.
=> :mortar_board: Topic16 Add download links to iterators and tests

src/test/java/ArrayIteratorTest.java
As discussed in #216 
Add `ArrayIteratorTest` to the repo. 
Emphasizing tests. 
I ran em'.
=> :mortar_board: Add ArrayIterator tests

src/test/java/LinkedIteratorTest.java
As discussed in #217 
Add `LinkedIteratorTest` to the repo
Because it's good to test. 
Yes
=> :mortar_board: Add LinkedIterator test

src/site/topic16.rst
Correct download link paths. 
I had the wrong path. 
Looks like only topic16, but there may be more.
=> :bug: Topic16 Fix download links

src/site/index.rst, src/site/lab5.rst, src/test/java/LinkedIteratorTest.java
Lab for building linked structures.
Because they will be using them a bunch.
=> :mortar_board: Lab5 --- linked structures

src/site/topic18.rst
Intro section for topic on memory. A warning is included that it's kept at a reasonably high level.
=> :mortar_board: Topic18 Intro for memory topic

src/site/index.rst, src/site/lab3.rst, src/site/lab5.rst, src/site/topic3.rst
Fixed various markup issues and broken download paths 
Sphinx told me to
Sphinx built happily (at leas, more happily)
There is still an issue in Lab3 saying there is an unexpected indent, but I think it may have to do with having
1. `code` at the end of a line
2. a sub point after the line
3. `code` starting the point
Either way, I'll ignore that for now.
=> :bug: Fix various issues

src/site/topic18.rst
Add heap section. 
Although I do go into more details on object space, I leave a note saying that we won't worry about that level of detail here.
=> :mortar_board: Topic18 Heap section

src/site/topic18.rst
Explination of garbage collection
Any additional detail is not really necessary since:
1. It won't matter for their level
2. May end up just confusing them
Though, if y'all think of something neat for an aside for the keeners, that's cool.
=> :mortar_board: Topic18 Garbage collection

src/site/topic20.rst
- Create the section layout to make git happy
- Add a few points to the top to remind me of stuff since I'm stopping for today
=> :mortar_board: Topic20 Section layout

src/site/topic21.rst
Add a single section for definitions. 
Only one section since the topic is gonna' be annoyingly definition heavy. It's more an intro topic to get us to binary trees and binary search trees. 
Luckily, tree definitions/terms are fairly intuitive
=> :mortar_board: Topic21 Add definitions section

src/site/topic22.rst
Add sections for binary trees. 
To make git happy with merges later. 
Some of the subsections _may_ change once I start filling things out.
=> :mortar_board: Topic22 Add sections for binary tree

src/site/topic23.rst
Layout the sections for the BST topic. 
To make git happier with merging later.
=> :mortar_board: Topic23 Add binary search tree topic sections

src/site/topic20.rst
Intro section for seraching
- Informally define searching
- Emphasize that it's a problem, not an algo
- Any algo that works is correct, but we will focus on two high-level ideas
Hitting the difference between problems and algos is critical at this stage as sometimes it can get too conflated.
=> :mortar_board: Topic 20 Add intro section

src/site/topic24.rst
Create sections for sorting topic
Makes it easier to merge 
Somewhere in this topic I will discuss stability and inplace. This will likely fall into place once the topic gets filled in. 
Also, trying to decide what level of detail should be hit. Will at least explain each one in english at a high level, but pseudocode or Java? The point is the _idea_ more than the implementation, though that could be said for everything in the content so far. Either way, I'll think on it.
=> :mortar_board: Topic24 Add sections for sorting

src/site/lab6.rst
Add lab 6 to the course content. Lab 6 buillds a `BadArrayQueue`, which is a queue using an array where the front is always zero. 
They're implementing an ADT with another implementation (although very similar to the one we focus on). They will also have to hack the tests for the `ArrayQueue` to work here, which is a good exercise too. 
Ideally this is a simpler lab where they will have time to try Kattis.
=> :mortar_board: Lab6

src/site/lab7.rst
Add lab 7 to course content. This requires them to implement a linked version of a `SortedBag`.
This one may be a lot to chew on, so there is no hard expectation for them to finish.
=> :mortar_board: Lab7

.github/workflows/gradle-build-deploy.yml
#6 
Rename workflow
Add aws action
Will enable auto-deploy 
Will do
Crossed fingers.
=> :robot: Update gradle-build-deploy.yml

.github/workflows/gradle-build-deploy.yml
#241 & #6 
Remove unzip command from deploy workflow. 
Update sync path to be `.`
Download artifact appears to uncompress for us.
=> :robot: Remove unzip and update sync dir

.gitignore, src/main/java/Assignment1.java
Start prepping A1 stuff. 
- Add solutions to gitignore
- Add a class (``Assignment1``) with a main for them to use and "test" their solutions
=> :memo: :mortar_board: Asn1 gitignore

src/site/index.rst
Merge **after** #249 
Add links to labs 6 -- 8 to the main page 
So people can access it
Although not necessary, deal with this *after* #249
=> :mortar_board: Add links to labs 6 -- 8 to index

src/site/lab8.rst
Add a lab focusing on recursion to the course content. 
Instructions are becoming more vague since, at this stage, they should be able to extrapolate
=> :mortar_board: Lab8

.gitignore, src/main/java/Assignment1.java, src/site/asn1.rst
#251 
Move the A1 solution to a package. 
Update gitignore to ignore folder
Remove asn* from gitignore since they will be assignment descriptions and they will need to be here
Add asn1.rst to repo. It's currently just, more or less, a template. 
It's better this way. I will make another folder under site with relevant downloadable content that can be in repo.
=> :memo: :mortar_board: Move A1 solution to a package

src/site/topic2.rst
=> :bug: fix typo `'` -> `;`

src/main/java/Assignment1.java, src/site/topic18.rst
Half the size of the stack overflow example image. 
1. it is ungodly big
2. 250px is the size of the stack gif, so it should match
=> :mortar_board: Topic18 Resize stack overflow example

src/main/java/Assignment1.java, src/site/topic19.rst
Start the iterative vs. recursive definitions. 
Also cutting the series of number example since it is the same as the group of people.
I am splitting this section to more than one PR to keep them manageable.
=> :mortar_board: Topic19 Start iterative vs recursive definitions

src/site/topic19.rst
Sililar to #258 
Remove extra whitespaces in the open backquote for the list example. 
Typesetting doesn't work.
=> :mortar_board: :bug: Topic19 Remove extra space again

src/site/topic19.rst
Remove the sum section.
The example ends up being the same as factorial and doesn't add any value to the content
I will rework `recSum` to be `recursiveFactorial` in the stack image.
=> :mortar_board: Topic19 Remove sum section

src/site/topic19.rst
- Add points about breaking the problem down over and over again 
- Add point about how it may feel like cheating, but really we keep applying the same thing over and over
-  Add examples of going 'up' and 'down' (for lack of better terms)
Breaking this section into mulriple PRs.
=> :mortar_board: Topic19 Breaking down problems and going 'up' vs 'down'

src/site/topic19.rst
Add some notes on a few simple, but important observations about recursion. There is an emphasis on recursion on our computers and recursion in general.
Although they hopefully connected the dots based on topic18, the point of emphasizing the stack ADT and the call stack is because, well, it is a stack, and it is useful. 
Including the point on recursion in general is important as many CS students conflate computers/computational systems with the boxes on our desks, when in reality, CS is much broader. 
Note on answering all the smaller questions (to know `recFact(4)` we need `recFact(3)`) isn't so much a BIG IMPORTANT NOTE (but neat nontheless), but it will get their mind on repeating work which will come up with fib numbers.
=> :mortar_board: Topic19 Add a few observations about recursion

src/site/topic19.rst
#265 
Add wording to emphasize that thye may find a particular recursive function easier to write, not that they are just intrinsically easier. 
It's better this way
=> :mortar_board: Topic19 Add clarity on recursive functions being 'easy' to write

src/site/topic19.rst
Introduce analysis of recursive functions section. Starts simple with linear. 
Compared the iterative analysis and recursive analysis of the factorial functions. 
This will lead into fib, which gives a chance to talk about exponential growth, how the algorithms are not only different in terms of iterative vs. recursion, but in _how_ they do their thing, but also binary trees, and how they grow too.
=> :mortar_board: Topic19 Introduce analysis section

src/site/topic19.rst
#261 
Remove extra spaces again from the list example. 
Add new lines between each example to get typesetting to work properly and place each subsequent step on new lines. 
Built the site locally and it checked out.
=> :mortar_board: :bug: Topic19 Fix list example again

src/site/topic20.rst
Introduce linear search. 
They already know this stuff, but it will be good to be talking about it more deliberately in this context 
- Give the _idea_
- Explain that the idea is fairly abstract
- Hit the complexity again
=> :mortar_board: Topci20 Introduction to linear search

src/site/topic20.rst
Show the iterative linear search and have a short discussion 
To talk about it in more detail than before 
Originally I didn't want to include actual code, but use pseudocode so I could use implementing it as a lab. After thinking about this, it's so trivially easy to google these that it's irrelevant if I use pseudocode or code on the topic page; it would make no difference.
=> :mortar_board: Topic20 Add iterative linear search

src/site/topic20.rst
Introduce a recursive linear search. 
Easy comparison of two algos solving a well understood problem
Show that the high level algo is the same.
They've actually already seen this in CS101 (161) when they see haskell, but they're likely not going to remember.
=> :mortar_board: Topic20 Recursive linear search

src/site/topic18.rst, src/site/topic19.rst
Closes #277 
Related to #276 
Move the example of debugging from the recursion topic to the memory topic. 
Eliminates any potential discussions on semantics 
Where discussing the stack.
=> 🎓 🆕 Move debugging example with Brian C video to memory topic

src/site/topic20.rst
Correct example of the average position for element in linear serach is 1/2 way. 
Remove "exact" from starting explination of recursive linear search
It originally said "2nd element" twice.
=> :bug: :mortar_board: Topic20 Correct explination of middle average

src/site/topic20.rst
#273 
Change terminology to `needle` and `haystack` for searching. 
Because it's effin' fantastic. 
In the code bits
=> :mortar_board: Topic20 Change to needle and haystack in content

src/site/topic20.rst
Add recursive binary search to content
Add small notes saying that the algo, other than being recursive, is ultimately the same idea
=> :mortar_board: Topic20 Recursive binary search

src/site/topic20.rst
Closes #286 
Add points on the use of _helper_ methods for the initial recursive call for both linear and binary searches. 
1. It's common
2. It will lead into the use of the helper methods in the subsequent topics on trees since they are used there. 
Only in the topic page. Was going to add them to the `SearchMethods` class, but opted to leave them out since it may slightly take the focus away from the seraches. Further, the use of helper methods will be used more in the tree topics. 
Added notes, but also added what the code would look like in code snippets.
=> :new: :mortar_board: Topic20 Add helper methods for recursion

src/site/topic20.rst
Add download links to the search methods and search methods tests 
So hopefully they look at it. 
End of topic
=> :mortar_board: Topic20 Add download links

src/site/topic21.rst
Add an intro section for the topic on trees. The tree topic is mostly focused on definitions/terminology
=> :mortar_board: Topic21 Introduction to trees

src/site/topic22.rst
Adds a new section for discussing the interface. It will ultimately be a short section. 
Adds download link to binary tree interface. 
Since I will not be going deep into a binary tree implementation, at least provide the interface. Further, this sets up the inheritance for the binary search tree in topic 23.
=> :new: :mortar_board: Topic22 Add binary tree interface section & download

src/site/topic22.rst
#296 
Add download link to bottom of topic page. 
It was supposed to be there in #296, but I apparently forgot to push the last commit.
=> :new: :mortar_board: Topic22 Add download link to binary tree interface

src/site/topic22.rst
Add a short intro to binary trees. 
Helps set up for _bi_-nary trees
Ended up being smaller than I expected.
=> :mortar_board: Topc22 Add intro to binary trees

src/site/topic22.rst
Review linear structure traversals
Demonstrate that there is no one obvious ordering to a traversal of a binary tree to setup the four popular traversals (pre, in, post, levelorder)
binary tree image is not in this PR as it was added in #299
=> :mortar_board: Topic22 Start traversals section

src/site/topic22.rst
Add a definition and example of a preorder traversal. 
binary tree example image is not in this PR as it was added in #299.
I also avoided pseudocode here since I will actually show them code later. I ended up using pseudopseudocode, to use the technical term.
=> :mortar_board: Topic22 Preorder traversal subsection

src/site/topic22.rst
Subsection describing the inorder traversal. 
Just copy/pasted the preorder traversal and made the changes. 
Again, binary tree image was added in #299
=> :mortar_board: Topic22 Inorder traversal subsection

src/site/topic22.rst
Add details and example of a postorder traversal. 
Copy/paste with necessary changes. 
Binary tree example image was added in #299
=> :mortar_board: Topic22 Postorder traversal subsection

src/site/topic22.rst
Do a quick computational complexity analysis of the traversals. They are kept intuitive without going any deeper into anything like t(n). 
Complexity analysis is important, but at this level of data structure, the discussion can be kept fairly high-level. Getting a sense of the relationships in values and complexity is the idea, not about setting proofs or anything.
=> :mortar_board: Topic22 Traversal computational complexity analysis

src/site/topic22.rst
Add discussion on changing the underlying collection from a queue to a stack in the level-order traversal and how that would affect the functionality. 
Helps with contrasting and comparing. Changing code slightly to do something different is cool too.
The section is left open ended as more of a discussion question.
=> :mortar_board: Topic22 Iterative version of traversals subsection

src/site/topic22.rst
Add details on the level order traversal.
Copy/paste from other traversals, but this one needed more massaging. 
I do not include a recursive version of the level order since it's complex, but an iterative one is used. This is awesome because it will lead into the iterative pre/in/post order traversals by changing out the data structure.
=> :mortar_board: Topic22 Levelorder traversal subsection

README.md
Add a link to a live version of the website. 
So people can find a version of it.
=> :memo: Add link to CSCI162 website to README

src/main/java/BinaryTree.java, src/site/topic22.rst
Add a short section discussing the interface for a `BinaryTree`. The section emphasizes that add and removed are not included.
Added the interface code without any comments.
=> :mortar_board: Topic22 Add interface section

src/site/topic19.rst, src/site/topic22.rst
Correctly name of the image to be displayed for fib. 
`recursion_recursiveFibonacci` --> `recursion_fibonacci`
It didn't load the picture due to the error.
=> :bug: :art: Topic19 Correctly name the image to be displayed for Fibonacci example

src/site/topic23.rst
Just references #327 
Explain how finding and/or removing the maximum value is nearly the same as finding and/or removing the minimum
Right under the details for minimum.
=> :mortar_board: Topic23 Finding and/or removing the max

src/site/topic23.rst
Fixes an issue created in #327 
Include the correct images for remove min
I originally was trying to use the general remove images that were not actually in the repo yet.
=> :bug::art: Topic23 Include the correct images for remove min

src/site/topic23.rst
Fixes bad sizes of images from #332 
Resize the images of a single tree to 250 to match all others
Too big and ugly.
=> :art: :telescope::lipstick: Topic23 Resize images for remove 

src/site/topic23.rst
Describe the idea behind contains and count of a given element. 
Contains is simple given the detailed description of binary serach above. 
Count is a little trickier, but still based on binary search. 
Because we will discuss implementations below. 
At this stage, the prep is for a linked implementation.
=> :mortar_board: Topic23 Contains & Count

src/main/java/LinkedBinarySearchTree.java, src/site/topic24.rst, src/test/java/LinkedBinarySearchTreeTest.java
Show the start of the binary serach tree class, including the fields and constructors. Also, fixes a bug in the 2nd constructor. Lightly discuss the constructors, but by this point of the course this should be straightforward for the students. 
The bug was in the 2nd constructor. The constructor takes a single element to set to the root of the tree, but it was setting the size to `0` as opposed to `1`. 
Looks like the tests failed to catch this (never used the 2nd constructor in tests :grimacing:)
=> :mortar_board::bug: Topic24 Constructors and class setup

src/site/topic24.rst
Show contains and binary search methods. Contains is the helper method
Just another chance to discuss binary search.
=> :mortar_board: Topic24 Contains & binary serach

src/site/topic24.rst
Add code and description for the recursive add method.
Discussion is kept brief as the ideas were introduced in Topic23.
=> :mortar_board: Topic24 Add 

src/site/topic24.rst
Show and explain the code for finding the minimum and maximum values in the binary search tree. 
Kept short since it was explained in more detail in Topic23.
=> :mortar_board: Topic24 Minimum and Maximum

src/site/topic24.rst
Cut the traversals section from the topic
The traversals will be the same as those discussed in Topic22. Although not all the code was shown there, they can download the `BinarySearchTree.java` file for reference. In other words, this section adds nothing.
=> :bomb::mortar_board: Topic24 Cut traversals section

src/site/topic24.rst
Explain the ``removeMin`` and ``removeMax`` methods. 
These functions are starting to get more complex, so going into more detail is good. 
More details will be hit while actually discussing the stuff.
=> :mortar_board: Topic24 removeMin and removeMax

src/site/topic24.rst
Show and discuss the `getCount` method for the linked implementation. 
They should see it. 
At this point, I will have had them use recursion to count things in a linear structure in a lab or something.
=> :mortar_board: Topic24 getCount discussion

src/site/topic2.rst
Replace the google link with a smaller one. 
It was gross. 
End of topic2, where I tell them that google exists.
=> :lipstick: Topic2 Make google link smaller

src/site/topic2.rst
Change the character var symbol from `e` -> `c` 
(a) that's what the comment says
(b) that's what I reference in the discussion
(c) because that's what I used in the Python example. 
For each example. 
This is also addressed in #352
=> :bug: Topic2 Fix symbol for character

src/site/topic2.rst
Fix the amount of indentation used in the for loop. 
It was in too far. 
For loop. 
Also addressed in #352.
=> :bug: :lipstick: Topic2 Fix indent in `for` loop

src/site/topic25.rst
Add a section for defining sorting. It's not overly formal, but it does go into the fact that the elements are the things that have the orderness property, not the algo or the collection. 
It helps to slow down and think about what sorting is in more detail. Sure, they all know what sorting is, but being deliberate helps. 
The point on orderdness is already discussed in ordered bag and binary search tree, so this is just a reminder.
=> :mortar_board: Topic25 Define sorting

src/site/outline.rst
* General formatting changes
* General updates for Winter 2022 semester. 
* Removed Java from topics
* Removed activities to avoid contact with other humans
* Added a warning about what would happen if things changed to remote 
Just prep for the semester.
=> :new: Outline In person outline for W2022

src/site/index.rst
General updates to time/place/names for Winter 2022 semester. 
Details are now "known" 
- The time of Lab 2 changed, which is weird. :shrug: 
- I will soon remove the WIP note at the top, despite still not being set.
=> :new: Index Updates for W2022

src/main/java/BinaryNode.java
Create a `BinaryNode` class for simple use in lab 9. 
Currently the `Node` class used for the binary tree stuff for lectures is a static nested class. This is great and all, but to make lab 9 easy, there will also be a regular ol' class called `BinaryNode` that is the same as the nested one.  
1. Copy
2. Paste
3. Rename `Node` -> `BinaryNode` to not conflict with the linear one. 
4. Remove extra stuff that came with copy
=> :mortar_board: Lab9 Create BinaryNode class

src/main/java/BinaryNode.java
Busted from #382 
Change all the private methods to public. 
So they can be used. 
I did a whoopsie
=> 🐛 Lab9 Change private to public

src/site/index.rst, src/site/lab2.rst, src/site/lab3.rst, src/site/lab4.rst, src/site/lab5.rst, src/site/lab6.rst, src/site/lab7.rst, src/site/lab8.rst
Remove extra space before url to kattis problem 7
There was an extra space, and it was bugging me. 
Kattis #7
=> :bug: Labs Remove extra space

src/site/lab1.rst
Replace the link to the old stfx url to be a relative link
It was pointing to a nonexistant website. 
Built local 
Must've missed this one after the original move.
=> :bug: Lab1 Fix link from old website to new

src/site/index.rst, src/site/lab9.rst
Create lab 9 up to:
- file exists
- added to index
- headings
- relevant code
Gotta' have a lab 9. 
Built local. 
Q: _Why are you doing Lab9 in such small bits? Why not do it all at once?_
A: Getting what you can done while having a child not break everything is a win.
=> :mortar_board: Lab9 Headings and Code

src/site/lab9.rst, src/site/topic21.rst, src/site/topic22.rst, src/site/topic23.rst
Finishes the lab started in #389 
Add the actual content to the lab. 
We need this lab.
Built local
=> :mortar_board: Lab9 Content

src/site/index.rst, src/site/lab10.rst
Create a lab 10 focusing on the "simpler" sorting algorithms 
As of now I am thinking that lab 11 will focus on quick and merge sort, so haveing a baseline is cool.
Built locally
1. Ended up going with arrays, but added a note that they could do it with bags if they want. This may be useless though. 
2. I mayyyyyyyyyyyy make another topic lab 10, and then make this one 11, but I'll see.
=> :mortar_board: Lab10

src/site/index.rst, src/site/lab11.rst
Create the base for lab 11
Copy/paste from lab 10 and change a few things. Biggest change was to the bags since I think the recursive sorts will be a lot easier with them instead of trying to do in place sorts on an array. 
Built locally
This was not the original branch I had for lab 11, but somehow it got out of whack, and it was easier to just copy/paste.
=> :mortar_board: Lab11 Skeleton

src/site/outline.rst
Change the late policy to allow late submissions for up to 7 days after the deadline with no penalty. 
I expect, with the way things are going this year, students will be requesting extensions more often. This allows for the extension without asking. 
Don't worry, I know.
=> :new: Outline Change late policy

src/site/lab11.rst
Finishes up the lab started in #392 
Complete the lab instructions. 
It's nearly a copy/paste of lab 10
=> 🎓 Lab11 Finish lab content

src/site/gettingset.rst
Add a link to google to the getting setup page
A number of students have asked specific questions about getting setup. Some are answerable, some require some digging that I am unable to do. 
This is just a reminder that they should and can likely solve these themselves --- something they're going to be doing a lot of. 
At the end of getting set. 
Slightly sarcastic link. 
It may annoy some students, but it's a painful exercise in realizing they are capable of solving these problems on their own.
=> :new: Gettingset Add link to google

src/site/index.rst, src/site/lab10.rst, src/site/lab11.rst, src/site/lab12.rst
Move labs around to make room for a new lab 10. 
I want to have 12 labs, and the last topic of the course are the more advanced sorts, but that was lab 11. There will now be a new lab 10 on heaps. 
Built local.
=> :lipstick: Labs Move labs 10 & 11 to be 11 & 12

src/site/lab1.rst
Add details to the note about java syntax help. 
Refresher that Google exists. 
Built local.
=> :new: Lab1 References for java

src/site/lab1.rst, src/site/topic2.rst
Link to actual IO part of the topic instead of just the topic page. 
Easier navigation
Built local.
=> :lipstick: Lab1 Link to IO section

src/site/asn1.rst
Introduce assignment 1's task, what they do, and what they are provided with. Also tell them to read the whole assignment. 
Gotta' start somewhere. 
Built local
=> :mortar_board: Asn1 Intro section of assignment 1

src/site/asn1.rst
Explain what what they are to do for Part 1 --- the country class. 
It's kept simple. 
Built local. 
I originally wanted to have the numbered items be not going past the line length specified for rst, but if you do that, then the numbering points get weird. I guess I'll keep the line length for the paragraphs and whatnot.
=> :mortar_board: Asn1 Add Country Class Part

src/site/gettingset.rst
Closes  #408 
Change Wither -> Either
It was a typo
=> :bug: GettingSet Fix spelling error Wither -> Either

src/site/asn1.rst
As discussed in #412 
- Change numbers in numbered list to use `#`
- Fix the name of the `Asn` class
- Fix typesetting for code like text
- Trying out the `#`
- Bug fixes
Built local
=> :lipstick: :bug: Asn1 Change numbered list to use `#` and typos

src/site/asn1.rst
The first half of the ``CountryCatalogue`` specifications. 
It's the collection. I also split it up because I didn't want it to get too big. 
Built local
There will be a bunch of other methods added for the 2nd half.
=> :mortar_board: Asn1 `CountryCatalogue` First Half

src/site/asn1.rst
Make a new part 4 about testing. 
Part 3 is now about a static method for loading the data from the files. 
Built local
Note that Part 3 is renamed in another PR coming later.
=> :mortar_board: Create Part4 Testing

src/site/asn1.rst
As discussed in #414 
Describe the static method for loading data from a file. 
It's better this way. Besides, it keeps the data structure and the use of the data structure seperate. 
The new method will be in the `Asn1` class
Built local
I will be making a new PR for removing the equals, hash, and the map from the CountryCatalogue
=> :mortar_board: Asn1 Load data from files static method

src/site/index.rst
Remove the WIP warning from the main page. 
It's nearly done, and I don't want to send the wrong message since it's... well... nearly done.
=> :bomb: Index Remove WIP Warning 

src/site/topic26.rst
Does some clean up of #401 
Add a section on recursive thinking
Clean up wording in previous sections to help with explination
Add future section titles
Because recursion is beautiful
Built local
=> :lipstick: :mortar_board: :telescope: Topic26 Quicksort Recursive Thinking

src/site/topic26.rst
Discuss good pivots and the algo analysis
Built local
=> :mortar_board: Topic26 Quicksort Good Pivots

src/site/lab10.rst
Describe minheap. 
It's kept somewhat highlevel because I want them to build it more on their own
Built local
Addidentally killed this branch, but was able to restore it. Huzzah
=> :mortar_board: Lab10 Minheap

src/site/lab10.rst
Explain bubbling up
Built local
I was going to make an image, or a gif or something to show this process, but that's a lot of work for right now. Maybe another time.
=> :mortar_board: Lab10 Heap Bubble Up

src/site/topic3.rst
Add a space between "two``Friend"
Didn't show right
=> 💄 :bug: Topic2 Fix space for formatting

src/site/lab10.rst
Explain bubble down
Built local
=> 🎓 Lab10 Heap Bubble Down

src/site/asn1.rst
Change the dude date to be 1 week later. 
Off to a slower start than anticipated. 
1. Chaos that was this semester so far
2. Missed classes due to movein day
3. Getting people up to speed with the online system
=> change due date

src/site/topic26.rst
Explain the complexity of building a min heap and removing from it to explain the overall complexity of heapsort
Topic 26, but it does make reference to Lab10 a lot. 
Originally this was going to just be the building half, but whatever.
=> 🎓 Topic26 heapsort complexity up

src/site/topic5.rst
Some cleaning up here and there. 
When lecturing, I noticed a few small things worth changing. I did a whole once over and found a few more things.
=> 💄 Topic5 Clean up content a tad

src/site/topic6.rst
Small formatting and wording changes. 
Saw small issues when lecturing. Also noticed a few small things of confusion, so slightly more details were added. 
I feel like there is one more big one I noticed in lecture that I have missed, but whatever.
=> 💄 Topic6 Small Cleanup

src/site/asn2.rst
Prepare the assignment description file. Mostly a skeleton. 
Will make it easier to fill in the blanks later.
=> :new: Asn2 Prepare the description

src/site/asn2.rst
Introduce the goal of the assignment.
=> 🎓  Asn2 Introduce Task

src/site/asn2.rst
Add titles to sections and add a new part, and a pecularities section. 
May seem frivolous, but this is this is for me and how I write things.
=> 💄 Asn2 Title Sections and More Sections

src/site/asn2.rst
Emphasize that a big part of the assignment is understanding the classes they get. 
A lot of times students just want to CODE CODE CODE CODE. It's good to remind them to slow down.
=> 🎓 Asn2 Part 1 --- Read More

src/site/asn1.rst, src/site/asn2.rst
Add a little more to the FAQ. 
Details to help them and me. Some wording may seound _nicer_. 
asn2, but I ctrl-c -> ctrl-v into asn1.
In the future, maybe make the FAQ a seperate page to eliminate redundancy?
=> :new: Asn1&2 Add to and Clean FAQ

src/site/topic7.rst
Just some general cleanup to the contents of topic 7
wordsing better
=> 💄 Topic7 Cleanup

src/site/topic6.rst
Fix the wording of the warning about implementing the interface. 
It wasn't a properly parsable sentence. 
Topic 6's warning about the IDE telling you that the interface is not fully implemented.
=> :bug: Topic6 Warning wording

src/site/asn2.rst
Discuss some specific methods and ideas.
Some of the stuff used in the assignment is entirely new to them. None of it is by anymeans inaccessible to them; they are capable of understanding how it works. I just feel it's going to be good to highlight particular ideas that may feel like curveballs. 
Near the end of the assignment description.
I think I hit the most noteworthy things. There are a few I opted not to go into.
I can make an argument to myself to remove the exceptions subsection as they probably can put two and two together here. 
Really, the only ones I see as important to really hit are the constructor related ones.
=> :new: Asn2 Noteworthy Code

src/site/asn2.rst
Tell them to run the tests for the provided code. 
So they know everything is working. Also, just experience running the unit tests.
=> :new: Asn2 Part2 Testing

src/site/asn2.rst
Explain what the main should do. 
I may be giving them too much help by saying "make a maze, a maze solver, and a renderer", but we'll see.
=> :new: Asn2 Describe main functionality

src/site/asn2.rst
Tell them to re run tests and run their main on different mazes. 
It's a good thing to do.
=> :new: Asn2 Part 5 Testing

src/site/asn2.rst
Explain how `solve` should work. 
I am aiming for:
* Ambiguous enough that they need to problem solve
* Clear enough that they are not lost in the woods
=> :new: Asn2 Explain `solve`s Functionality

src/site/index.rst
Add a link to assignment 2's description to the main page. 
Easier for the students to get to it that way.
=> 🎓 Asn2 Add to Index

src/site/asn2.rst
Clean up of wording and typesetting. 
Correctness and clairity
Throughout 
Did a once over
=> 💄:bug: Asn2 General Cleanup

build.gradle, src/test/java/ArrayStackEqualsTest.java
As mentioned by @twentylemon in #475 
Include the tests for equals in the `ArrayStack` class. 
It should be there. 
Created a new special test class for equals. This keeps it seperate from the other tests. 
That's what this is. 
Will do this first, then add the others to the other PRs.
=> :new: `ArrayStack` `equals` Test Class

src/main/java/LinkedStack.java, src/main/java/Node.java, src/test/java/LinkedStackEqualsTest.java, src/test/java/LinkedStackThoroughTest.java
1. Add equals and hash to `LinkedStack`
2. ~Add equals and hash to inner `Node` class of `LinkedStack`~
3. ~Add equals and hash to not inner `Node` class~
4. Copy/paste the thorough tests from `ArrayStackThoroughTests` 
5. Remove `expandCapacity` test
Consistency with `ArrayStack` and its tests. ~I also changed the regular ol' `Node` class to be consistent with the inner one for the `LinkedStack`~
Yes. 
I will also be re-doing the `ArrayQueue` and `LinkedQueue` accordingly.
=> 🆕:telescope: Linkedstack Thorough Tests

src/main/java/LinkedQueue.java, src/test/java/LinkedQueueEqualsTest.java, src/test/java/LinkedQueueThoroughTest.java
Equals and tests for `LinkedQueue`
Consistency 
Yes. 
This assumes the other PRs are good. If they change, this will change.
=> :new::telescope: `LinkedQueue` `equals` and Tests

src/main/java/ArrayQueue.java, src/main/java/ArrayStack.java, src/main/java/LinkedQueue.java, src/main/java/LinkedStack.java
Addresses some of #480 
Clean up the hashcode of the stack and queue implementations. 
They were not great, and also inconsistent. 
Yep
=> 💄 Change the stacks' and queues' `hashCode`

src/site/lab4.rst
Remove extra period in the middle of a sentence in a link. 
It should not be there.
=> :bug: Lab4 Remove Extra Period

src/site/asn3.rst
Start the asn3 description page
For the assignment 3
Copied asn2's over and gutted it.
=> 🎓 Start making asn3's description page

src/site/data/Assignment2/test/DfsMazeSolverTest.java
Change `DfsMazeSolvertEST` -> `DfsMazeSolver`
It's wrong the way it is. 
Unclear how/when this happened, but obv when I made edits to the assignment stuff in prep for release. I checked the other repo and it's fine there.
=> 🐛 Asn2 Fix `DfsMazeSolverTest`

src/site/asn3.rst
Explain the task/goal of the assignment. 
Gotta' start somewhere.
=> 🎓 Asn3 Task Section

src/site/asn3.rst
Explain that they should read. 
They never do
Copy/paste from asn2
=> 🎓 Asn3 Part 1 --- Read

src/site/asn3.rst
Have them run the complete unit tests for the maze package. 
1. Gets their project setup to test
2. They can learn from it
3. They know the existing code works
Mostly copy/paste from asn2.
=> 🎓 Asn3 Part 2 Early Tests

src/site/asn3.rst
Explain the main method. 
Mostly copy/paste from Asn2
I'm leaving the middle parts for later because I'm tired
=> 🎓 Asn3 Part 5 Putting it Together

src/site/asn3.rst
Have them re-run all their tests. Also remind them to write them for the 2 classes. 
Mostly copy/paste from asn2
=> 🎓 Asn3 Part 6 Testing Again

src/site/asn3.rst
Explain the priority queue part of the assignment. 
I broke it down into subsections that I think will help make this part more bite-size.
=> 🎓 Asn3 Part 3 Priority Queue

src/site/asn3.rst
Give details on how to go about writing the `AStarMazeSolver`. 
I want them to figure much of this out on their own, but I give enough details that they should feel comfortable starting. 
I originally included the private methods I wrote as I thought it may help give them ideas, but I feared they would get too focused on those private methods and get stuck into a certain way of thinking.
=> 🎓  Asn3 Part 4 A Star

src/site/asn2.rst
Change W -> w
It is a typo
High level DFS description
=> :bug: Asn2 change W -> w

src/site/asn3.rst
Chance assignment name from "Using Artificial Intelligence" -> "A Better Path is Also a Path"
It's more in line with assignment 2's title
=> 🆕 Asn3 Change Assignment Name

src/site/index.rst
Add asn3 to the index
So they can access the details
=> 🎓 Asn3 Add link to assignment on main page

src/site/asn3.rst
Mention that they can totally use private methods
Sometimes they worry about adding extra stuff. I figure it's good to encourage them now that the problems are getting complex enough. 
Somewhat related to the comment on private methods in #498
=> :new: Asn3 Private Methods

src/site/asn1.rst, src/site/asn2.rst, src/site/asn3.rst
#460
Remove extra word 
"capable of learning ~learn~ on your own"
it's not a sentence
All assignment FAQs 
#460 will help with this going forward
=> 💄 :bug: Asns FAQ Remove Extra Word

src/site/asn4.rst
Copy over the assignmment description page from Asn3 and make the necessary changes. It's just a skeleton page at this point. 
Gotta' start somewhere.
=> 🎓 Asn4 Create Description Page

src/site/asn4.rst
List the files that they get
The download link and warnings were already here
=> 🎓 Asn4 Provided Files

src/site/asn4.rst
=> 🎓 Asn4 Task

src/site/topic9.rst
Incorrect growth function
Incorrect function will give incorrect results
Line 46 in topic9.rst
Change t(n) = 15n^{2} + 25n
to...
t(n) = 15n^{2} + 45n
=> 🐛 Update topic9.rst

src/site/asn4.rst
Tell them to go read up on Huffman Codes. Give them a few key things to look out for when learning about it. 
I want them to go learn about how they work on their own (or together, I don't care). This exercise is part of the assignment.
=> 🎓 Asn4 Part1 Read About Huffman Codes

src/site/asn4.rst
Describe the comparator part. 
I provided the level of detail I did since this is somewhat new to them at this stage, and since the order is critically important, I mention it here just in case they didn't catch that when learning about Huffman Codes.
=> 🎓 Asn4 Part3 ``HuffmanNodeComparator`` 

src/site/asn4.rst
Explain what they are to do for the node classes. 
They will need to have a good idea of huffman codes to really get to this, but I want enough details that they can put it all together.
=> 🎓 Asn4 Part 2 ``HuffmanNode`` classes

src/site/asn4.rst
Remind them to run their tests
This is mostly to emphasize the importance of the tests
=> 🎓 Asn4 Part6 Testing

src/site/asn4.rst
Explain what their main method should do. 
Help them finish it off. They've done the heavy lifting. Now it's a matter of using what they built. 
Unlike previous assignments where I mentioned `RELATIVE_PATH`, I exclude that here as they should have an idea of what this is by now.
=> 🎓 Asn4 Part5 ``main``

src/site/asn4.rst
Explain how to implement the ``HuffmanCode`` class. 
Similar to other parts of the assignment, I provide some detail to help, but am expecting them to have a good understanding of the compression strategy based on Part 1.
=> 🎓 Asn4 Part4 ``HuffmanCode``

src/site/asn4.rst
Fix a link in asn4
It was broken onto two lines, so it didn't work.
=> :bug: Asn4 Fix Link

src/site/asn4.rst, src/site/lab4.rst
Closes #522 
Change SKeleton -> Skeletal 
Words better. 
Intellj's "find in files" is actually great. 
I had thought I used the word more, but I guess not 🤷
=> 🔭 💄 Change Skeleton

src/site/data/Assignment2/src/Maze.java, src/site/data/Assignment3/src/maze/Maze.java
Update the header to remove the real time symbols used. 
They are not used anymore. They originally were part of the idea, but they were cut. 
An update to the other repo is coming.
=> 🐛:bomb: Maze Remove Update Header

src/main/java/ObjectsPlaying.java, src/main/java/PlayingObjects.java, src/site/topic3.rst
Related to #77 
Related to #479
Make the playing code downloadable. Also make use of `:literalinclude:` 
- It's better to just be able to download it. 
- `literalinclude` will defo help with consistency going forward
Built local
I added line numbers back in. Originally they were cut to make for easy copy/paste, but I like being able to reference line numbers when talking about stuff.
=> :lipstick: Topic3 Playing Code Download

src/main/java/PlayingArrayStack.java, src/site/topic6.rst
Related to #77 
Related to #479
Make the playing code downloadable. Also make use of `:literalinclude:` 
- It's better to just be able to download it. 
- `literalinclude` will defo help with consistency going forward
Built local
I added line numbers back in. Originally they were cut to make for easy copy/paste, but I like being able to reference line numbers when talking about stuff.
=> 💄 Topic6 Playing Code Download

.github/dependabot.yml
Add dependabot to the repo.
Because it was so much fun the first time.
=> 🤖 📝 Add dependabot to Repo

src/site/topic13.rst
Change is -> of
typo --- sentence doesn't make sense as is.
=> :bug: Topic13 Typo: is -> of

src/site/cpp-arrays.rst
Starts #309
Start the topic on arrays
I have no good answer to this
=> :new: 🎓 Cpp Arrays

src/site/topic14.rst
Closes #550 
Add new lines 
Spacing was bad --- will render better now. 
Did this during lab as example.
=> :bug: Topic14 Add New Lines For Formatting

src/site/cpp-arrays.rst
Closes #309
Describe dynamic arrays
Feels like I should mention it I guess. 
1. I added a section on the heap to basically say that I am not going into it, but here is some trivia. 
2. I propose a new emoji for the Cpp asides 💩
=> 🎓 🆕 💩 Cpp Dynamic Arrays

src/site/index.rst
Add cpp arrays to index
So people can find it.
=> :new: 🎓 💩  Add Cpp Arrays to Index

src/site/lab7.rst
Add a download link to the bag interface in lab 7. 
They need it --- easier access.
=> 💄 Lab7 Add Download Link to Bag

src/site/topic14.rst
Closes #546
Change "has code" to "hash code"
Typo
Done in lab as an example
=> :bug: Topic14 it's hasH code

src/site/topic3.rst
Closes #560 
Remove extra comma
=> :bug: Topic3 Remove Comma

src/site/topic16.rst
Change the `<Integer>` to `<T>` in the `toString` example
=> 🐛 Topic16 <Integer> -> <T>

src/main/java/Bag.java
change occured to occurred
:new: :bomb: :mortar_board: :memo: :robot: :lipstick: :bug: :telescope: :art: Add relevant emojis to title. [See style guide.](https://github.com/jameshughes89/cs102/blob/main/CONTRIBUTING.md#style-guidelines).
Typo in Bag.java occured to occurred
because grammar is nice
Bag.java file above the getCount in
However you can fix it
=> 🐛 Typo in Bag.java (occured -> occurred)

src/site/cpp-pointers.rst
Add a note similar to the vector one in arrays about how smart pointers are better.
1. In terms of what _they_ want, they say that they want them to know cpp
2. But they don't actually. They want them to know one level of cpp
3. This is all dumb anyways
I checked out `auto_ptr`. Apparently that's old now.
=> :new: Cpp Pointers Add Note on Smart Pointers

src/site/asn3.rst
Remove "Priority" from "LinkedPriorityQueue".
Incorrect
Assignment 3 page, under part 3.
Backspace
=> 💣 🎓 🔭 Asn3 Part 3  - "LinkedPriorityQueue" -> "LinkedQueue"

src/site/topic19.rst
Remove unnecessary "Factorial" header.
Not supposed to be there.
Topic #19, under recursion
Backspace
=> 💣 🎓 🔭 Topic #19 - Unnecessary "Factorial" header

src/site/topic19.rst
=> :lipstick::bug: Topic19 Cleanup

src/site/lab8.rst
Reorder the steps in the lab to have factorial first. 
We covered it in lecture, so it's a good starting point. Then hopefully they see the point that it's a change in a character to do sum.
=> 💄 Lab8 Put Factorial Before Sum

src/site/asn3.rst
closes #577 
changed fell to feel
annoying
=> :bug: Assignment 3 fell to feel

src/site/topic20.rst
Add closing parenthesis
Incorrect without it
Topic #20 under Binary Search, right above Iterative
Type
=> 🎓 🔭 🐛 Missing closing parenthesis

src/site/asn3.rst
Add "as" to the specified sentence
Looks funky otherwise
Assignment #3, under Part 4 "Implementing the Class"
Type it
=> 🎓 🔭 "as many.. you need" -> "as many.. as you need"

src/site/topic23.rst
Remove period at end of sentence
Consistency
Topic 23, last sentence before "A Binary Search Tree is a Binary Tree" under "Binary Search Tree Definition"
Backspace
=> 💣 🎓 🔭 Punctuation fix

src/site/topic20.rst, src/site/topic23.rst
Change "binaryContains" to "binarySearch"
Makes code incorrect, is inconsistent otherwise
Topic 23, in the block of code under "Binary Search"
Type
=> 🎓 🔭 "binaryContains" -> "binarySearch"

src/site/topic24.rst
Remove period at end of sentence "Create a nested node class aside."
Consistency
Topic 24, under Static Node Class
Backspace
=> 💣 🎓 "Create a nested node class aside." -> "Create a nested node class aside"

src/site/index.rst
Remove the stuff from the end of the index page. 
It's dumb.
=> :bomb: Index --- Remove end stuff

src/site/index.rst
Change the semester at the top of the index to read Winter 2023. 
Time is linear and has a direction
=> :mortar_board: Index --- Change year to 2023 :microscope: :microscope: 

src/site/index.rst, src/site/outline/outline.rst
General updates for Winter 2023 
1. Change dates and rooms and stuff
2. Add recoupment
3. Ditch 7 day late thing for assignments
4. Labs have no marks now 
5. Lower assignment weightings 
6. Add another test and no makeup tests
7. Copy/paste general end stuff from 101 (161)
1. Because
2. I liked it. It gets them to actually look at their feedback
3. It sucked last year --- it worked out exactly as I had knew it would in the back of my mind; late date was just the due date and people complained about too close due dates :facepalm:. Anyways, it was only really there to deal with the uni's requested policy for the semester on covid sickness, which was to just always give extensions extensions extensions with no evidence. Turns out this became a big issue for most profs that had no hedge …
=> :mortar_board: Course Changes --- Winter 2023

build.gradle, src/site/topics/java-vs-python/java-vs-python.rst
Move the java vs python code into tables so they are side by side. 
Looks nicer 
List table 
Built locally a bunch. Looks pretty. 
1. This is *not* a clean up of the topic content. This PR is mainly focused on moving code into tables. A subsequent PR will do the general onceover. 
2. Although the `list-table` was used, this is *not* a PR focused on moving all tables to list tables (#169)
3. I snooked an update to sphinx in since the site would not build locally on my other lappy
=> 💄 Java vs Python --- Move code into tables

src/site/topics/stacks/array-stack.rst
Partially kills #625 
Fix the broken link to the chaining aside in the array stack topic
=> :bug: Chaining Aside --- Update the reference to it in the array stack topic

src/site/_static/css/custom.css
Adds a little more to #626 
Update the top mobile bar colour. 
It was left to be boring ol' blue. 
Built local; looks nice
=> :lipstick: Theme --- Change colour to red some more 

src/site/topics/collections/collections.rst
Cleanup of content for the Collections topic
Good to do yearly. 
Built locally, looked good.
=> :mortar_board: Collections Topic --- Cleanup :broom: 

src/site/topics/stacks/stack-adt.rst
This does not address #30 or #31 
Clean up the stack topic 
General yearly cleanup
Built locally, looks good
It does switch the `push` to return a boolean, which is from #638
=> :mortar_board: Stacks ADT Topic --- General Clean :broom: 

src/main/java/ContactList.java
Improve the comments in the `ContactList` class
1. They could be better
2. Since it's the first collection they see in Java, I figure things could be a little more verbose
=> :technologist: :lipstick:  ContactList --- Improve comments

src/site/topics/objects-review/chaining.rst
Changed based on #640 
Clean up of constructor chaining aside 
Yearly clean
=> 💄 Constructor Chaining Aside --- Clean 🧹 

src/main/java/ContactList.java, src/test/java/ContactListTest.java
1. Add messages to the exceptions
2. `get` specifies the issue in the message (negative, or too big). 
3. Add tests for exception messages to tests
:+1:
=> :lipstick: ContactList --- Improve exceptions

src/main/java/ContactList.java, src/site/topics/objects-review/equals.rst
1. Clean up the equals aside
2. Add a note about a few ways of checking "equality" 
1. yearly clean
2. Good to note
Built the site locally, looks good (though the note is a little janky looking with all the code-like text, but meh).
=> 💄 Equals aside --- Clean 🧹 

src/site/assignments/maze-solver-too/Assignment3/test/maze/MazeRendererTest.java, src/site/assignments/maze-solver-too/Assignment3/test/maze/MazeTest.java, src/site/assignments/maze-solver/Assignment2/test/MazeRendererTest.java
Indent the top row of the maze
So it aligns nicely.
=> 🔭  Maze Tests --- Move start of top row

src/main/java/Friend.java, src/site/topics/objects-review/objects-review.rst
Clean the first portion of the Objects Review topic. This mostly deals with the `Friend` class. 
There were also small changes to the `Friend` class
1. Add a comment saying that the things are fields 
2. Change the bad equals to be _correct_ 
General yearly clean and also update based on the changes to the ``Friend`` class 
Kept building locally, looked good. 
There will be a subsequent PR. This one was getting wayyy too big. 
I was considering ditching the equals aside to include the proper equals in the main topic, but that would be way too much info. The topic is already too much as is. If anything, in the future, I may want to consider breaking this topic into two.
=> 💄 🎓 Objects Review Topic --- Clean Friends bit 🧹 

.github/workflows/gradle-build-deploy.yml
Change the java version in the action from 11 -> 17
17 is a bigger number than 11, so it must therefore be better.
Bad diff --- it's just the 11 -> 17.
=> 🤖 Github Action Java Version --- 11 -> 17

src/site/topics/objects-review/builder.rst
Change the code to be from a literal include. Also update the warning to be accurate. 
1. consistency --- Im attempting to do this everywhere where possible
2. It the code updates, the topic code will not get out of sync with small changes (though, it totally still could get out of sync if the code blocks grow).
Built local, looks good.
=> 💄 🔭 🎓  String Builder Aside --- Change to use literal include for code

src/site/topics/objects-review/chaining.rst
Change the code block to be a literal include. 
1. consistency --- I am trying to do this wherever possible
2. If there are small changes to the source code, then this will not need to be updated (though, large changes can mess these includes up if they grow larger). 
Built local, looks good.
=> 💄 🔭 🎓 Constructor Chaining Aside --- Change to literal include code block

src/main/java/Stack.java
Related to #657 
Change a few words around in the interface's documentation to be consistent with the queue. 
consistency
=> 🔭  👩‍💻 Stack Interface --- Clean a little more 🧹 🔬 

src/main/java/ContactList.java, src/main/java/Friend.java, src/site/topics/objects-review/equals.rst
1. Change to use the literal include for the code
2. Also add doc comments to the `ContactLIst` equals
3. Also add `@Override` for consistency 
- consistency --- I am trying to do this wherever possible
- If there are small changes to the source code, then this will not need to be updated (though, large changes can mess these includes up if they grow larger).
Built local, looks good. 
Although this aside will probably be removed and incorporated into the main content, this will help with copy/pasting.
=> 💄 Equals aside --- Change to literal include code block

src/main/java/ArrayStack.java, src/main/java/LinkedStack.java
Change on the stack -> in the stack
Consistency with interface and other data structure wording. I realize _on_ the stack also works, but so does _in_.
=> :telescope: Stack Implementations --- Change on -> in :microscope: 

.github/workflows/gradle-build-deploy.yml
Update python version from 3.9 to 3.11
=> 🤖 Python version --- 3.9 -> 3.11

src/site/topics/stacks/stack-adt.rst
1. Make generics its own section
2. emphasize generics differently 
3. Fix underline 
1 & 2. Easier to find
3. bugfix (warning fix)
:+1:
Built local, looks good.
=> 🎓 💄 Stacks ADT Topic --- Adjust sections

src/main/java/PlayingArrayStack.java, src/main/java/PlayingLinkedStack.java
Change the exception type being caught to be the correct type (`EmptyCOllectionException`) 
It was updated in other PRs. 
Ran locally and it worked.
=> 🐛🧑‍💻  Stack playing code --- Change exception type

src/site/topics/stacks/array-stack.rst
Clean the array stack topic
Yearly clean
:+1: Built local --- looks good.
=> 💄 🎓 ArrayStack topic --- Clean 🧹 

src/site/index.rst
Remove the links to the assignments
They may change (assignment 1 defo will) and I don't want the keeners to solve the wrong thing. 
:+1: --- built local, looks good.
=> 💣 Index --- Assignment links

src/site/index.rst
Remove mention that office hours are virtual only
They are not virtual at all
=> :bug: Office Hours --- Not virtual only :microscope: 

src/main/java/ArrayQueue.java
Change on -> in 
consistency with all other wording
=> :telescope: ArrayQueue --- Change on -> in :microscope: 

src/site/topics/stacks/array-stack.rst
Change the section titles when they correspond to a method name, make them `likeThis`
Consistency with other topics
=> :telescope: Array Stack Topic --- Make section titles more code like

src/site/topics/objects-review/objects-review.rst
1. Do another pass over the topic to ensure it works as a standalone topic
2. Move the equals details from the aside to the main topic here
1. Things were moved (#666), so it needs to be consistent
2. Bad equals was dumb anyways. Having spent more time on classes in the previous course, this is good stuff here. 
:+1: Built local, looks good. 
The equals aside will be removed _after_ the subsequent topic (the data structures topic) is re-cleaned.
=> 💄 🎓 Objects Review Topic --- Clean... Again... 🧹 

src/site/topics/objects-review/data-structures-review.rst
Make the section titles more `code like`
Consistency with other topics. Also, I like it this way. 
=> :lipstick: :telescope: Data Structures Topic --- Make section titles code like

src/site/topics/objects-review/data-structures-review.rst
Mentioned in #680 
1. Add download link to the test class for 
2. Warn that the tests will not be discussed
1. So they can see
2. Because the first collection I want to talk about testing on is the `ArrayStack` since it will be a lot easier. 
=> :new: :mortar_board: Data Structures Topic --- Warn about no test discussion

src/main/java/Node.java, src/test/java/NodeTest.java
Clean the node class' code. It ended up just being a slight change to the javadoc. 
Yearly clean, and consistency 
Copy/pasted from the private inner classes in the `LinkedStack` (or was it `LinkedQueue`?)
:+1: --- I made a test class for the Node class. 
*NOTE:* it only checks the get/sets for when data exists/does not exist. There are no tests for the different constructors. Should there be? Like --- `getData_defaultConstructor_returnsNull` & `getData_dataConstructor_returnsData`
=> :lipstick: :woman_technologist: Node Class --- Clean :broom:

src/main/java/ArrayIndexedBag.java, src/test/java/ArrayIndexedBagEqualsTest.java, src/test/java/ArrayIndexedBagTest.java
- Clean up the array indexed bag class
- Add equals tests
- Add actual good tests
- Yearly clean
- Should have been there
- Tests were not great before 
:+1:
=> 💄 🧑‍💻 Array Indexed Bag Class --- Clean

src/test/java/ContactListTest.java
Change `Stream<Arguments>` to `Stream<Friend>` 
Arguments is not needed. 
:+1:
=> 💄 🔭 Contact List --- Remove unnecessary use of `Arguments` in stream for test 🔬 

src/site/topics/stacks/array-stack.rst
1. Update text of the file to download
2. Remove the reference to the unittesting aside since it's being moved to not be an aside
3. Rearrange things into the list for downloading
=> :lipstick: Array Stack Topic --- Fix up end of topic content

src/site/labs/objects-collections/objects-collections.rst
Clean the objects & collections lab
Deliberately not adding this lab to the index yet. Depending on how the first week of lectures go, there may be a need for a lab between the hello world lab and this lab.
=> :lipstick: :mortar_board: Objects & collections lab --- Clean :broom: 

src/site/topics/testing/unit-test-collections.rst
#690 
1. Address some of the complexities with testing collections.
2. Add high-level sections for future easy merging. 
3. Add the ending stuff to the topic
I liked @twentylemon's suggestion in #690 about how to improve the _flow_ of the topic to help with general motivation of the testing strategy. 
1. They do be like that 
2. Makes future merges easier
3. It is the same as before
The content explaining the issue is copy/pasted from #690 
Built local, looks good. 
As mentioned in #690, I think it'll be easier to do this in a series of smaller PRs.
=> :new: :mortar_board: Unit testing collections topic --- Motivate

src/site/outline/outline.rst
Improve wording in the labs section of the course outline 
To make it more obvious that there is nothing to submit.
=> :lipstick: Outline --- Change wording under labs section

src/site/assignments/country-catalogue/country-catalogue.rst
Clean the intro of the assignment up
1. Yearly clean
2. The assignment is a litttttle different from before 
:+1:  built local, loos good
Although this now cleaned portion of the assignment contains a link to the provided files, this PR does **not** update the actual assignment files.
=> 🎓 Assignment 1 --- Clean intro 🧹 

src/site/assignments/country-catalogue/country-catalogue.rst
Clean up the end part of the assignment ('testing' section to 'what to submit' section)
FAQ part is done in #701
=> :lipstick: :mortar_board: Assignment 1 --- Clean end bit :broom: 

src/site/assignments/country-catalogue/country-catalogue.rst
Remind them that they will probably need to add JUnit to the project 
:+1: built local, looks good. Checked link, it worked.
=> :lipstick: Assignment 1 --- Mention adding junit to class path :microscope: 

src/site/assignments/country-catalogue/country-catalogue.rst
Explain `main` and what they should do with it. 
:+1: built local, looks good, link works.
=> 💄 🎓 Assignment 1 --- Explain `main`

src/site/topics/testing/unit-test-collections.rst
Note how the expected behavious may differ depending on the state.
Seems like a good segue to the example tests on for an empty stack, which is the immediate subsequent section.
=> :mortar_board: Unit Testing Collections Topic --- Motivate a little more :microscope: 

src/site/index.rst
Adds a link to assignment 1 to the index.
So the students can get to it.
Will not merge until #709 is merged.
=> :mortar_board: Assignment 1 --- Add link to index

src/site/assignments/country-catalogue/country-catalogue.rst, src/site/index.rst
Remove the "Assignment 1" from the title of the assignment and just have the website number things. 
It's better this way, and consistent with the other course and labs and topics in this course.
=> :telescope: Assignment 1 --- Rename and number assignments :microscope: 

src/site/topics/testing/unit-test-collections.rst
#690
- Discuss tests under the state of an empty stack 
- Show setup code with `@BeforeEach` 
:+1: built local, looks pretty good.
=> :new: :mortar_board: Unit Testing Collections Topic --- Test empty stack

src/site/topics/intro/introduction.rst
Small cleanup 
- Make the double quotes look different
- Remove period 
Cleaner and more consistent
=> :lipstick: :mortar_board: Intro topic --- Small cleanup :microscope: 

src/site/index.rst, src/site/labs/objects-collections/collections.rst, src/site/labs/objects-collections/objects.rst
Closes #437
Splits the objects & collections topic into 2
The pace at the beginning of the semester just isn't quite there to hit objects & collections all in one. Sure they are already aware of these ideas from the previous semester, but the flow just seems like it will be better this way, especially since there is a testing topic between the objects & collections topics now. 
=> :lipstick: :mortar_board: Objects & Collections Labs --- Split 

src/site/topics/testing/unit-test-collections.rst
#690 
- Explain singleton tests
- Explain nested classes
- Note that the push/newTop tests are useless 
=> :new: :mortar_board: Unit Testing Collections Topic --- Test singleton stack

src/site/topics/testing/unit-tests.rst
=> :bug: :mortar_board:  Unit test topic --- Remove comma :microscope: 

src/site/topics/objects-review/objects-review.rst
- Make data not have anything special with typesetting
- Make the word "method" italics, not boldfaced 
Consistency with both bits (function vs. data)
=> :lipstick: :mortar_board: Objects review topic --- Typesetting :microscope: 

src/site/index.rst, src/site/labs/unit-tests/unit-tests.rst
General clean up of the lab. Starts with the `Course` now and then moves to `CourseList` 
Although this lab will almost certainly happen before the topic on testing collections occurs, I think this will work out quite nice. They will have a chance to try to test the collection before shown the tricks discussed in the topic, thus, when they get to the topic, they will hopefully see the strong motivation.
=> :lipstick: :mortar_board: Unit tests lab --- Clean :broom: 

src/site/topics/queues/queue-adt.rst
Related #103
Clean up the queue topic 
The rotating cipher example is kinda' lame. This is already brought up in #103, however, the rotating cipher is left here for the cleaning process.
=> :lipstick: :mortar_board: Queue Topic --- Clean :broom: 

src/site/topics/objects-review/objects-review.rst
=> 🐛 Objects Review Typo

src/main/java/BinaryNode.java, src/test/java/BinaryNodeTest.java
1. Clean up class doc
2. Add another constructor
3. Add unit tests
1. It's better now (and was also wrong before) 
2. Perhaps useless, but it will be consistent with the regular `Node` class discussed 
3. Tests good
:+1:
This class is not actually used, but a copy/paste of it was a nested class in the `LinkedBinarySearchTree` class. In other words, that class will get a copy/paste update of this class once merged.
=> :lipstick: :telescope: :technologist: `BinaryNode` --- Clean :broom: 

.gitignore
Add the playground package to gitignore 
So I can play 
I moved things that were ignored into there and they are ignored, so, huzzah.
=> :memo: Gitignore --- Ignore playground package :microscope: 

src/site/assignments/country-catalogue/country-catalogue.rst
Warn about dividing by zero resulting in infinity, which is good
A few students have been a little thrown off by this. 
Honestly, after changing it, I'm not sure if it's cleared things up or if it's potentially made things more confusing.
=> :lipstick: :mortar_board: Country Catalogue Assignment --- Warn about infinity 

src/site/topics/linked-structures/linked-structures.rst, src/site/topics/objects-review/data-structures-review.rst, src/site/topics/objects-review/objects-review.rst, src/site/topics/queues/queue-adt.rst, src/site/topics/stacks/array-stack.rst, src/site/topics/stacks/linked-stack.rst, src/site/topics/stacks/stack-adt.rst, src/site/topics/testing/unit-test-collections.rst, src/site/topics/testing/unit-tests.rst
#77 
1. Make the playing code a subsection of "For Next Time"
2. Put all the reference to code to download and tinker with under the playing code subsection
3. Make the playing code downloadable, as discussed in #77 
Consistency and clarity 
1. This does notresolve #77 as this is only up to the topics that have been cleaned up for the year
2. The branch was only for one of the topics (objects review), but I expanded it to just do them all.
=> :lipstick: :telescope: :mortar_board: Early Topics --- Update playing code sections

src/site/outline/outline.rst
#621 --- changed to list table 
1. Set the date for the first test to be Feb 1
2. Change the table in the outline to be a list table 
=> :mortar_board: Test 1 --- Set date in outline :microscope: 

src/site/assignments/country-catalogue/country-catalogue.rst
Add a due date for the assignment 
1. They need a due date
2. This is 2 weeks today
As of now, in the course, we're basically finished the _Objects Review_, meaning that, with this pace, the _Data Structure Review_ will be done by the end of this week. Typically I like to have 2 weeks after the topics are fully introduced, however, data structures are not new ideas to them and the _Data Structure Review_ topic is a _review_. Further, I am aiming to have the first test take place Feb 1, which is the Wednesday after the asn1 due date. This is perfect as the assignment is ideal prep for the test.
=> :mortar_board: Country Catalogue Assignment --- Due Date :microscope: 

src/site/topics/algorithm-analysis/amortized.rst
Clean up the aside on amortized complexity 
=> :lipstick: :mortar_board: Algorithm analysis amortization aside --- clean :broom: 

src/site/topics/queues/array-queue.rst
Clean up the first part of the array queue topic
Only the first half because it's a bigger topic.
=> 💄 🎓 Array Queue --- Clean ideas 1 & 2

src/site/topics/testing/unit-tests.rst
Change "sufficient" to "fine" 
"Sufficient" was used earlier in the paragraph. Given this, it sounded _weird_. 
:-1: yolo
=> :lipstick: :mortar_board: Unit test topic --- Replace a word :microscope: 

src/main/java/PlayingObjects.java, src/site/index.rst, src/site/labs/stacks/stacks.rst
=> :lipstick: :mortar_board: Stack Lab --- Clean :broom: 

src/site/outline/outline.rst
#745 
Add due date to outline 
I honestly thought I had done this in #745, but :shrug:
=> :mortar_board: Outline --- Add assignment 1 due date :microscope: 

src/site/topics/stacks/stack-adt.rst
Remove a period at the end of a point. 
I have been avoiding using punctuation like this on the points. 
:-1: YOLO
=> :telescope: :mortar_board: Stack ADT Topic --- Remove period :microscope: :microscope: 

src/site/topics/stacks/stack-adt.rst
Warn about primitive types & generics 
To give them a heads up. 
I originally had it as a "note", but I opted to go with "warning" since (a) it could go either way and (b) it contrasts nicely with the directly proceeding note.
=> :new: :mortar_board: Stack ADT Topic --- Warn about primitive types & generics 

src/main/java/ContactList.java
Change ++i to i++
Consistency is key
=> :telescope: :technologist: ContactList change ++i to i++

src/site/topics/queues/array-queue.rst
Add question marks
They are questions after all
=> 🎓 Array Queue --- Add question marks to question 🔬 

src/site/topics/queues/array-queue.rst
Add a brief discussion about the `equals` for the array queue
1. I think it's interesting that there is a chance to talk about t what does and does not matter in equality (array capacity and where in the array the contents are do not matter)
2. There _was_ a section on testing that kinda' hit the _what does and what does not matter_ but was made moot by the cleaned up tests. Now this can be hit again. 
=> 🆕 🎓 Array Queue Topic --- Discuss `equals`

src/site/topics/objects-review/data-structures-review.rst
"ContactList" -> `ContactListTest" 
The link for the test class had a bad name.
=> :bug: :mortar_board: Data Structures Review --- Fix test class download link name

src/site/topics/queues/expand-capacity.rst
Clean up the `expandCapacity` aside for the `ArrayQueue` 
Biggest change was removing some of the last points as it seemed that they made things less clear. 
=> :lipstick: :mortar_board: `expandCapacity` aside --- clean

src/site/topics/stacks/stack-adt.rst
:bug:
Fix typo in stack-adt.rst under the maze example.
Consistency between code snippets and their descriptors
=> Update text in stack-adt.rst

src/site/topics/stacks/stack-adt.rst
Change Pseudocode -> Algorithm 
It's really not pseudocode
=> :lipstick: :mortar_board: Stack ADT Topic --- Pseudocode -> Algorithm 

src/site/topics/bags/bag-adt.rst
=> :lipstick: :mortar_board: Bag ADT Topic --- Clean :broom: 

src/site/labs/unit-tests/unit-tests.rst
Updated grammar
Grammar is important
An English professor verified grammatical correctness
=> :bug: :mortar_board: Testing Lab --- "thorough" -> "thoroghly"

src/site/assignments/maze-solver/maze-solver.rst
Clean up the description of the DFS maze assignment. 
- This does **not** update the assignment files to be downloaded. This will be done in a subsequent PR.
- This does **not** update index as that will come after the assignment files are updated. 
- The due date is TBD for the time being
=> :lipstick: :mortar_board: DFS Maze Solver --- Clean description :broom: 

src/site/labs/linked-structures/linked-structures.rst
Clean linked structure lab 
Not added to index yet as the pace of the course is still hard to figure out
=> 💄 🎓 Linked Structure Lab --- Clean

src/site/labs/queues/queues.rst
Clean the queue lab 
:+1: built local, looks good 
Not added to index yet as the pace of the course is still hard to figure out
=> 💄 🎓 Queue Lab --- Clean 🧹 

src/site/labs/sorted-bags/sorted-bags.rst
Clean bag lab 
Not added to index yet as the pace of the course is still hard to figure out
=> 💄 🎓 Sorted Bag Lab --- Clean 🧹 

src/main/java/BinarySearchTree.java, src/main/java/BinaryTree.java, src/main/java/LinkedBinarySearchTree.java, src/test/java/LinkedBinarySearchTreeTest.java
1. Clean up the `BinaryTree` interface
2. Clean up the `BinarySearchTree` interface (turns out it never extended `BinaryTree`) 
3. Update the implementation to make it happy
4. Update tests based on the changes to the interface and the consequential changes to the implementation 
:+1:
There will be a subsequent PR to clean up the actual implementation and tests. I have a feeling testing a nonlinear collection will be ugly.
=> :lipstick: :technologist: Binary Tree & BST Interface --- clean

src/main/java/ArrayIndexedBag.java, src/main/java/ArraySortedBag.java, src/main/java/Bag.java, src/main/java/IndexedBag.java, src/main/java/SortedBag.java
1. Change names of classes in docs to be lower case for consistency 
2. Use the word "element" instead of "target"
3. rewrite the remove in the sorted bag interface such that it has a more meaningful doc for the sorted bag 
:+1:
=> :lipstick: :technologist: Bag Interfaces --- Clean a little more

src/site/labs/stacks/stacks.rst
Function -> method
They're methods 
In spite of the offline discussion, it's a method, not a function.
=> :bug: :mortar_board: Stack Lab --- Function -> Method :microscope: 

src/test/java/LinkedIteratorTest.java
General cleanup of the linked iterator stuff (only the tests though as the implementation was fine).
:+1:
1. I opted to include the line `Node<Integer> head ... ` in each test, even when simply `null` as I felt the code was clearer that way
2. Much simpler to test than the array iterator
=> :lipstick: :technologist: Linked Iterator --- Clean :broom: 

src/main/java/BinarySearchTree.java
In the class doc, mention that the order is defined by the elements.
It will be a little more consistent with the class doc for the sorted bag. 
Copy, paste, edit the details from the sorted bag. 
:+1: because why not.
=> :lipstick: :technologist: BST Interface --- Improve class doc on order :microscope: 

src/main/java/LinkedQueue.java, src/main/java/LinkedStack.java, src/main/java/Node.java
Change Node -> node in class doc 
Consistency with other classes.
=> :telescope: :technologist: Node --- Use lower case in class doc for node :microscope: 

src/site/assignments/maze-solver/Assignment2/Assignment2.iml, src/site/assignments/maze-solver/Assignment2/src/ArrayStack.java, src/site/assignments/maze-solver/Assignment2/src/Asn2.java, src/site/assignments/maze-solver/Assignment2/src/DfsMazeSolver.java, src/site/assignments/maze-solver/Assignment2/src/Stack.java, src/site/assignments/maze-solver/Assignment2/src/maze/Cell.java, src/site/assignments/maze-solver/Assignment2/src/maze/LocationNotInMazeException.java, src/site/assignments/maze-solver/Assignment2/src/maze/Maze.java, src/site/assignments/maze-solver/Assignment2/src/maze/MazeEndpointsException.java, src/site/assignments/maze-solver/Assignment2/src/maze/MazeRenderer.java, src/site/assignments/maze-solver/Assignment2/src/maze/MazeSolver.java, src/site/assignments/maze-solver/Assignment2/test/ArrayStackTest.java, src/site/assignments/maze-solver/Assignment2/test/DfsMazeSolverTest.java, src/site/assignments/maze-solver/Assignment2/test/maze/CellTest.java, src/site/assignments/maze-solver/Assignment2/test/maze/MazeRendererTest.java, src/site/assignments/maze-solver/Assignment2/test/maze/MazeTest.java, src/site/assignments/maze-solver/maze-solver.rst, src/site/index.rst, src/site/outline/outline.rst
1. Update the assignment files 
2. Set the due date
3. Add link to assignment on index
The due date is later than I would have preferred, but it's fine. Reading week pushes it back a week as I do not want the due date during reading week. If the assignment was up earlier, like this past Monday, I would've had it due on the Monday _before_ reading week --- Feb 13th.
=> :mortar_board: DSF Maze Assignment --- Add assignment files, due date, and link to index :warning: 

src/site/topics/inheritance/careful.rst
General cleanup. 
I was considering reworking the example to not use setters, but then that would break the example, and I don't really think it's worth the effort to come up with a different example.
=> :lipstick: :mortar_board: Inheritance Aside (Square/Rectangle) --- Clean :broom: 

src/site/topics/iterators/iterators.rst
Clean the iterator topic 
:+1: built local, looks good 
As of now, although brought up in #799, I do not think I will move this topic _before_ bags. Seems good where it is.
=> :lipstick: :mortar_board: Iterator topic --- Clean :broom: 

src/test/java/LinkedBinarySearchTreeTest.java
Replace the new/empty tests.
Right now the whole test class is a mish-mash. It needs to be improved and it should be consistent with the other test classes using the nested test classes. 
:+1:
This PR only includes the empty tests. A subsequent PR will include the singleton tests, etc. ~Equals tests will be done separate too.~
They are being separated as I believe it will make getting the unit tests right a lot easier.
=> :lipstick: :technologist: `LinkedBinarySearchTreeTest` --- Replace empty tests

src/site/topics/algorithm-analysis/algorithm-analysis.rst
1. Removed extra `*`
2. Added some commas to help with reading the sentence 
1. typo
2. Improves readability
=> 🐛 🎓 Algorithm analysis topic --- Fix typesetting of some words 🔬 

src/main/java/SearchingFunctions.java, src/site/topics/searching/searching.rst
Clean the intro and linear search portion of the topic 
I snuck in a change to the respective class to remove a useless comment.
=> :lipstick: :mortar_board: Search functions topic --- Clean intro and linear :broom: 

src/site/topics/searching/searching.rst
Clean the binary search portion of the topic 
=> :lipstick: :mortar_board: Search functions topic --- Clean binary search :broom: 

src/site/topics/algorithm-analysis/algorithm-analysis.rst
Remove period from a point
I do not like the periods on points
=> :telescope: :mortar_board: Algorithm analysis topic --- Remove period :microscope: 

src/site/index.rst
Add a link to the queue lab to the main page
=> :mortar_board: Queue lab --- Add link to index :microscope: 

src/site/assignments/maze-solver/maze-solver.rst
Explicitly mention the 4 directions to check (up, right, down, left). 
Seems like I never did, and I had someone just ask if they should check diagonals 
Just added a point in the pseudocode-ish area
Oddly, no one asked last year :shrug:
=> :mortar_board: Maze DFS --- Mention 4 directions 

src/site/assignments/maze-solver-too/Assignment3/Assignment3.iml, src/site/assignments/maze-solver-too/Assignment3/src/LinkedPriorityQueue.java, src/site/assignments/maze-solver-too/Assignment3/src/PriorityQueue.java, src/site/assignments/maze-solver-too/Assignment3/src/Queue.java, src/site/assignments/maze-solver-too/Assignment3/test/AStarMazeSolverTest.java, src/site/assignments/maze-solver-too/Assignment3/test/LinkedPriorityQueueTest.java, src/site/assignments/maze-solver-too/Assignment3/test/maze/CellTest.java, src/site/assignments/maze-solver-too/Assignment3/test/maze/MazeRendererTest.java, src/site/assignments/maze-solver-too/Assignment3/test/maze/MazeTest.java, src/site/index.rst
- Update the assignment handout files
- Add a link to the assignment description to the index 
:+1: checked artifact, everything seems good
=> :mortar_board: A* maze solver --- Update assignment files and add link to index

src/site/assignments/huffman-codes/Assignment4/Assignment4.iml, src/site/assignments/huffman-codes/Assignment4/resources/seed_string.txt, src/site/assignments/huffman-codes/Assignment4/src/Asn4.java, src/site/assignments/huffman-codes/Assignment4/src/HuffmanCode.java, src/site/assignments/huffman-codes/Assignment4/src/HuffmanLeaf.java, src/site/assignments/huffman-codes/Assignment4/src/HuffmanNodeComparator.java, src/site/assignments/huffman-codes/Assignment4/test/HuffInternalTest.java, src/site/assignments/huffman-codes/Assignment4/test/HuffLeafTest.java, src/site/assignments/huffman-codes/Assignment4/test/HuffmanCodeTest.java
Update the handout files for assignment 4
Checked artifact. Looks good.
=> :mortar_board: Huffman code assignment --- Update handout files 

src/site/assignments/maze-solver-too/maze-solver-too.rst
Rename the assignment from Maze Solver --- A Better Path is Also a Path -> Maze Solver *Too* --- A Better Path is Also a Path
To make it more obvious that it's not assignment 2 --- I can imagine people not paying attention, having briefly looked at Assignment 2, opening up Assignment 3 and thinking it's the 2nd assignment. This name change helps makes it more obvious that it's different.
=> 💄 🎓 A* maze solver --- Rename assignment 🔬 

src/site/topics/sorting/sorting-basic.rst
=> :lipstick: :mortar_board: Searching Topic --- Clean :broom: 

src/site/topics/inheritance/inheritance.rst
Add new lines between points and subpoints 
With the theme used this year, if any subpoint is directly below a point, it boldfaces the text in the parent point
=> :bug: :mortar_board: Inheritance Topic --- Add newlines for typesetting :microscope: 

src/site/assignments/huffman-codes/Assignment4/src/HuffmanCode.java, src/site/assignments/huffman-codes/Assignment4/src/HuffmanInternal.java, src/site/assignments/huffman-codes/Assignment4/src/HuffmanLeaf.java, src/site/assignments/huffman-codes/Assignment4/src/HuffmanNodeComparator.java
Update the handout files based on the updated files from the assignment repo. 
I forgot to merge the updated files in the other repo before doing #856
=> :mortar_board: HuffmanCode assignment --- Update handout files again

src/site/labs/bags/sorted-bags.rst
=> :bug: Bag Lab --- Fixed sorted array lnk

src/site/topics/sorting/sorting-recursive.rst
Clean the other sorting topic 
I believe this is the last major "cleaning" PR for the year.
=> :lipstick: :mortar_board: Sorting More Topic --- Clean :broom: :partying_face: 

src/site/topics/bags/bag-implementations.rst
=> 🐛 🎓 Bag Implementation Topic --- Typo :microscope: 

src/site/topics/iterators/iterators.rst
Change contained -> container 
It should be containeR
=> :bug: :mortar_board: Iterator topic --- Contained -> container

src/main/java/ArrayIndexedBag.java
Change to use `Objects.equals`. 
1. it's better
2. consistency 
:+1:
=> :telescope: :technologist: `ArrayIndexedbag` --- Change to `Objects.equals` for `find`

src/site/labs/stacks/stacks.rst
- Fix the name of the stack adt topic
- Fix the link to the stack topic
=> :bug: :mortar_board: Stack Lab --- Fix link :microscope: 

src/site/index.rst
Add a link to the assignment to the index
=> :mortar_board: Huffman Code Assignment --- Add to index

src/site/labs/iterators/iterators.rst
Add a note about the order the elements are returned for the `ArrayStack`. 
It's not that it's _wrong_ if it's in one order or the other. The note is just to note that it _could_ matter.
=> :mortar_board: Iterator Lab --- Note the order elements are returned for `ArrayStack` :microscope: 

src/main/java/SortedBag.java
Update the doc comment for the `remove` method regarding the exception being thrown if it's an empty bag. 
Exception may be thrown if it's an empty bag OR if the element does not exist. 
:+1: because why not
=> :technologist: `SortedBag` interface --- Update `remove` doc RE empty bag exception :microscope: 

src/site/topics/recursion/recursion.rst
Change `++i` to `i++` in a for loop
Consistency
=> :mortar_board: :telescope: Recursion topic --- Change `++i` -> `i++` :microscope: 

src/site/index.rst
=> :mortar_board: Recursion Lab --- Add to index :microscope: 

src/site/topics/searching/searching.rst
Fix the line numbers for the code examples for the binary search. 
They were off by one. 
subtracted 1
=> :bug: :mortar_board: Searching Topic --- -Fix binary search example line numbers :microscope: 

src/site/index.rst
Add the binary tree lab to the index 
:+1: built local, ,looks good
=> :mortar_board: Binary Tree Lab --- Add to index :microscope: 

src/site/topics/trees/binary-search-trees.rst
Fix the line numbers to include for the algo 
They were off by 5
=> :bug: :mortar_board: Binary Search Tree Topic --- Fix algo lines :microscope: 

src/site/topics/trees/binary-trees.rst
Fix the recursive calls in the in order and post order traversals
They were wrong 
Student noticed during lecture
=> :bug: :mortar_board: Binary Tree Topic --- Fix recursive method calls :microscope: 

src/site/assignments/huffman-codes/huffman-codes.rst
`HuffmanCode` -> `HuffmanNode` 
Typo. 
Chanced a C to an N
=> :bug: :mortar_board: Huffman Code Assignment --- `HuffmanCode` -> `HuffmanNode` :microscope: 

src/site/topics/sorting/sorting-basic.rst
Add the starting state for the example phase 3 for bubble sort. 
Consistency, and also it's better.
=> :lipstick: :telescope: :mortar_board: Sorting Topic --- Add starting spot for phase 3 on bubble :microscope: 

src/site/index.rst, src/site/outline/outline.rst
Update the professor information for Fall 2023.
James is not teaching the section of Fall 2023.
Changes are in index.rst and outline.rst
=> Update the index and outline for fall 2023.

src/site/index.rst
Update the index for Winter 2024
Update title of the course, who is the prof, and times. 
:+1: 
Also added new line white space between sections because I liked having 3 lines before a next section.
=> :mortar_board: :arrow_up: Index --- Update for Winter 2024 Semester :microscope: 

src/site/assignments/country-catalogue/country-catalogue.rst, src/site/assignments/huffman-codes/huffman-codes.rst, src/site/assignments/maze-solver-too/maze-solver-too.rst, src/site/assignments/maze-solver/maze-solver.rst
Set due dates for assignments to be TBD
Idk when I want them due yet.
=> :mortar_board: :arrow_up: Assignments --- Make due dates TBD for Winter 2024 :microscope: 

src/site/outline/outline.rst
Update the outline for Winter 2024
- Names of things
- Prof name
- Times and places
- Make it more in line with 161
=> :mortar_board: :arrow_up: Outline --- Update for Winter 2024

src/site/topics/intro/introduction.rst
Remove the word "simple"
It should have been "simply", but I opted to remove the word either wya
:-1: YOLO
I also added new lines since I prefer having 3 before a new main section
=> :bug: Intro --- Remove word "simple" :microscope: 

src/site/topics/objects-review/objects-review.rst
Remove the word "just" from a sentence 
shout out to @twentylemon 
:-1: YOLO
=> :lipstick: :mortar_board: Objects review --- remove "just" word :microscope: 

src/main/java/ArrayIndexedBag.java, src/main/java/ArrayIterator.java, src/main/java/ArrayQueue.java, src/main/java/ArraySortedBag.java, src/main/java/ArrayStack.java, src/main/java/BinaryTree.java, src/main/java/ContactList.java, src/main/java/Friend.java, src/main/java/LinkedBinarySearchTree.java, src/main/java/LinkedQueue.java, src/main/java/LinkedStack.java, src/main/java/SearchingFunctions.java, src/site/topics/algorithm-analysis/algorithm-analysis.rst, src/site/topics/algorithm-analysis/amortized.rst, src/site/topics/bags/bag-implementations.rst, src/site/topics/exceptions/exceptions.rst, src/site/topics/iterators/iterators.rst, src/site/topics/objects-review/chaining.rst, src/site/topics/objects-review/data-structures-review.rst, src/site/topics/objects-review/objects-review.rst, src/site/topics/queues/array-queue.rst, src/site/topics/queues/linked-queue.rst, src/site/topics/searching/searching.rst, src/site/topics/stacks/array-stack.rst, src/site/topics/stacks/linked-stack.rst, src/site/topics/testing/unit-tests.rst, src/site/topics/trees/binary-search-trees.rst, src/site/topics/trees/binary-trees.rst, src/site/topics/trees/linked-binary-search-trees.rst, src/test/java/FriendTest.java
Closes #479 
Add tags to relevant bits of code and replace all the line numbers in the `literalinclude` with tags
code moves, line numbers get messed up, braking the website 
Slowly
:+1: 
I did one block at a time. It was... painful... 
Noticed #943 along the way.
=> :lipstick: :technologist: :mortar_board: `literalinclude` --- Use tags for better referencing of code

src/site/labs/hello-world/hello-world.rst
Remove extra period
Other bullets in section don't have periods
=> :medal_sports: :bug: Remove extra period from "Hello, World!" lab

src/site/assignments/country-catalogue/country-catalogue.rst
Closes #785
1. Add a due date for the assignment 
2. Clear up what I want the getters to be called and what the name of the population density method should be named
1. They need a due date
2. Although the getters are perhaps more obvious, some students were calling it `getPopulationDensity`, which is reasonable, but would cause the tests to fail. Most figured it out, but being clearer up front is better. 
YOLO
=> :lipstick: :mortar_board: Country catalogue assignment --- Due date and clear up method names

src/site/topics/objects-review/data-structures-review.rst
Closes #763 
Move the discussion of `size` and `isEmpty` up in the topic
Although not a big deal, every year some students are thrown by the use of these methods in other methods discussed earlier despite not having talked about them yet. 
Replace this text with a detailed description of where the change is/should be and why (should it be an aside?). 
If the where is obvious because of _Files changed_, then you don't fill this in. 
Just moved it up to be the first methods discussed 
:+1:
=> :lipstick: :mortar_board: Data structure review --- Move `size` and `isEmpty` up

src/site/outline/outline.rst
Add test 1's date to the outline 
YOLO
=> :mortar_board: Outline --- Test 1 Date :microscope: 

src/main/java/ContactList.java
Move the tag in the code to be above the imports
The text in the course notes mentions the imports, so by moving the tag up, we actually include the imports. 
I _could_ have updated the course notes to not mention the imports, but at this stage of the semester I think it's good to explicitly mention them and show them. 
YOLO
=> 🎓 👨‍💻 💄  Contact List/Topic data structures review --- Move tag before imports  🔬 

src/main/java/ContactList.java
Remove `final` from method
Doesn't need to be there and students were asking about it, meaning it was distracting 
:+1:
=> :bomb: :technologist: ContactList --- Make `hashCode` not final :microscope: 

src/site/assignments/maze-solver/maze-solver.rst
Add a due date for the assignment
=> :mortar_board: Maze Solver Assignment --- Set due date Winter 2024 :microscope: 

src/site/assignments/maze-solver-too/maze-solver-too.rst
=> :mortar_board: Assignment Maze Solver Too --- Due date Winter 2024 :microscope: 

src/site/outline/outline.rst
Add test 2's date
:-1: 
March 13th is totally the end of feb
=> :mortar_board: Outline --- Test 2 2024 date :microscope: 

src/site/assignments/huffman-codes/huffman-codes.rst
Set the due date
Last day of classes (which is a Monday, but a Friday)
=> 🎓 Assignment Huffman Code --- Due Date W2024 🔬 

src/site/topics/searching/searching.rst
=> :bug: :mortar_board: Topic searching --- Fix page number typo :microscope: 

src/site/topics/trees/binary-search-trees.rst
Fix the height of the empty tree to be -1
That's how we've been defining it
=> :bug: :mortar_board: Topic binary search tree --- Fix height of empty tree :microscope: 

src/site/assignments/country-catalogue/country-catalogue.rst, src/site/assignments/huffman-codes/huffman-codes.rst, src/site/assignments/maze-solver-too/maze-solver-too.rst, src/site/assignments/maze-solver/maze-solver.rst, src/site/index.rst, src/site/outline/outline.rst
Update course information, and assignments date.
Start of Fall 2024.
- Index
- Outline
- Assignments
Change the current information.
=> :mortar_board: Update information for Fall 2024

src/site/outline/outline.rst
Set the date of the midterm
It's the wednesday before reading week, but after the 2nd assignment is due. 
:-1:
=> :mortar_board: Midterm --- Set date winter 2025 :microscope: 

src/site/assignments/maze-solver/maze-solver.rst
=> :mortar_board: Assignment maze solver --- Set due date winter 2025 :microscope: 

src/site/assignments/maze-solver-too/maze-solver-too.rst
Add a due date for A3
branch name says 2, but it really is A3
=> :pencil2: Assignment 3 --- Due Date 2025 :microscope: 

src/site/assignments/huffman-codes/huffman-codes.rst
=> :memo: Assignment 3 huffman code-- Due date winter 2025 :microscope: 

src/site/assignments/huffman-codes/huffman-codes.rst
Fix the link to the comparator 
It was linked to a comparable.
=> :bug: :memo: Assignment huffman --- Fix link to Comparator :microscope: 

src/site/topics/sorting/sorting-basic.rst
Mention that the worst case scenario is when the smallest element is at the wrong end 
It's more specific 
A student pointed it out in lecture, which was nice.
=> 🐛 🎓 Topic sorting --- Bubble sort worst case scenario 🔬 

src/site/assignments/country-catalogue/country-catalogue.rst, src/site/assignments/huffman-codes/huffman-codes.rst, src/site/assignments/maze-solver-too/maze-solver-too.rst, src/site/assignments/maze-solver/maze-solver.rst, src/site/index.rst, src/site/outline/outline.rst, src/site/outline/schedule.rst
Prepare the course website for Summer 2025
:+1: Built local, looks good
=> :baby: Summer 2025 --- Prep website
