jameshughes89/cs102

src/site/topic5.rst

Typo on genetics->generics.  Added void to examples for consistency

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

#81 
Correcting the link to the contributing guidelines. They were linking to a non-existent branch.
404 ded bad.
Rich diff view.er

:bug: correct link to `CONTIBUTING` in templates

---

CONTRIBUTING.md

Closes #89 
Change the good first issue label's emoji to :medal_sports: `:medal_sports:` from :baby: `:baby:`. Also threw in a change in the text from "image" -> "images" to match the plural of "figures" used. 
The baby :baby: may be interpreted negatively and may discourage participation if individuals feel that they are being insulted. Was going for :1st_place_medal: `:1st_place_medal:`, but that was too long for the label text. 
CONTRIBUTING.md
There is nothing to change in templates as it was not included in the emoji list.

:memo: Change :baby: to :medal_sports: for "good first issue" label

---

src/site/conf.py
src/site/topic9.rst

Add subsection to Topic9 on growth functions. 
Add a warning about how we focus on growth & change. 
Change imgmath to mathjax in conf.py.
imgmath is switched for mathjax as it does not depend on LaTeX.
Topic8
conf.py
Since I am using `:math:` in a bunch of places, I did some local tests to see how things rendered. :lipstick:

:mortar_board: Topic9 Add section on growth functions

---

src/site/topic10.rst

Add a section on the abstract queue operations: `enqueue`, `dequeue`, and `first`. 
Topic10.rst
[It was decided to use the traditional naming for queue operations.](https://en.wikipedia.org/wiki/Queue_(abstract_data_type))

:mortar_board: Topic10 Add section on queue operations

---

src/site/topic8.rst
src/test/java/ArrayStackTest.java
src/test/java/LinkedStackTest.java

Ensure function names start with lower case.
Follows convention. 
As of now, two functions started with `Pushing...`. 
LinkedStackTest.java
ArrayStackTest.java
topic8.rst

:bug: Fix function names in stack tests

---

src/main/java/ArrayStack.java
src/main/java/LinkedStack.java
src/site/topic6.rst
src/site/topic8-nested.rst
src/site/topic8.rst
src/site/topic9.rst
src/test/java/ArrayStackTest.java
src/test/java/LinkedStackTest.java

Closes #107 
Replace the use of `EmptyStackException` for everything dealing with stacks. Also added messages to `NoSuchElementException`.
Although not needed, I think this will help with consistency :telescope:.
I also want to avoid  the question _why is there no_ `EmptyQueueException` _?_ 
Messages were added to the message to show that it's a thing. 
src/test/java/LinkedStackTest.java
src/test/java/ArrayStackTest.java
src/main/java/ArrayStack.java
src/main/java/LinkedStack.java
/src/site/topic6.rst
src/site/topic8.rst
src/site/topic8-nested.rst
src/site/topic9.rst
`grep -R "EmptyStackException" .`
Ran `grep -R "EmptyStackException" .` again.

:telescope: :mortar_board: Change `EmptyStackException` to `NoSuchElementException` for stacks

---

src/main/java/ArrayStack.java

Change `size` to `initialCapacity` for creating the array in the `ArrayStack` constructor. Also format code and eliminate whitespace.
Although not _wrong_, size may get confused with capacity. 
size is also used for the queues. 
src/main/java/ArrayStack.java

:telescope: :lipstick: Use `initialCapacity` for `ArrayStack` constructor

---

src/main/java/ArrayStack.java
src/main/java/LinkedQueue.java
src/main/java/LinkedStack.java
src/site/topic6.rst
src/site/topic8.rst

Currrently there is a newline character being added at the end of the `toString`. Remove this. 
No need for it. 
src/main/java/ArrayStack.java
src/main/java/LinkedStack.java
src/main/java/LinkedQueue.java
/src/site/topic6.rst
The extra newline is left in the `ContactList` example since it is too much effort to address and may just throw off the students starting out.

:bug: :lipstick: :telescope: Remove extra \n at end of `toStrings` for data structures

---

src/site/topic11.rst
src/site/topic3.rst
src/site/topic6.rst
src/site/topic8.rst

Remove the `:linenos :` from the playing code. 
If someone tries to copy/paste the code to play with it, they will get the line numbers too, making usign the code a real pain. 
Literally only delete `:linenos:` from the `code-block`s
Although this is being done, #77 will still be a thing.

:mortar_board: Remove line numbers from playing code for easy copy/paste

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Add a note to the where template letting people know not to worry about "Where" when it is obvious due to _Files changed_.
Seems silly and a waste of resources
Templates! :thinking: 
The "Where" probably makes more sense for the Issues template, but I can see it popping up in PRs every now and then.

:memo: Add note to templates on Where heading

---

src/site/topic11.rst
src/site/topic12.rst
src/site/topic6.rst
src/site/topic8.rst

Closes #140
Remove the newline before the `catch` statements.
More typical formatting
Up to topic 12 and topic 16.
ctrl + f
Should not be a problem in any of the .java files if using the formatter. As of now, without a formatter for the .rst files (#155), it may get missed within the topic pages.

:lipstick: :telescope: Update try/catch statements 

---

src/main/java/ArraySortedBag.java

Replace the `>` to a `<` when using `.compareTo`. 
Found a bug in a commented out version of the `findInsertIndex` method when looking for the proper intex to insert something. 
`ArraySortedBag`

:bug: :mortar_board: Fix a greaterthan/lessthan issue

---

src/main/java/BinarySearchTree.java

Remove the `toString` from the `BinarySearchTree` interface. 
Not needed. 
`BinarySearchTree` interface. 
I found it and hit the backspace button.

:telescope: :mortar_board: Remove `toString` from `BinarySearchTree` interface

---

src/site/topic7.rst

Add a warning about emphasizing the difference between a Node and a referrence ot a Node. 
Although at this point they should be well aware of the difference between references and objects, this does still come up as a common area of confusion. 
Topic7 because that's the first place where links are referred to.

:new: :mortar_board: Topic7 Add warning about head not being a node

---

src/site/lab2.rst
src/site/lab3.rst
src/site/lab4.rst

Change "refer to the slides" -> "refer to the topic pages"
Remove the period in the first point and move stuff after period to sub-point
There ain't no slides. 
I don't like the periods

:bug: Fix lab intros

---

.github/workflows/gradle-build-deploy.yml

#246 #241 #6 
Change source to simply be `./source` instead of `./source/*`.
Because it's my next guess. Also because [docs](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html#examples) seem to suggest it's the dir I specify anyways
Nope.

:robot: Change source for aws sync

---

src/site/topic20.rst

Change `O(n)` -> `O(1)` for constant time. 
Constant time is currently written incorrectly as `O(n)`

:bug: :mortar_board: Topic20 Fix constant time symbols

---

src/main/java/SearchingMethods.java
src/site/topic20.rst

Closes #287 
Change the recursive binary search to simply pass altered values as parameters for the recursive cases instead of modifying the original parameter values and passing them to the recursive case.
In other words, instead of modifying the value of, for example, `lowIndex = midpoint + 1`, just call the recursive function with `recursiveBinarySearch(needle, haystack, midpoint + 1, highIndex);`
It's nicer this way. 
Tests were re-run to make sure nothign went wrong. :+1: 
Is this needed? No. 
Do I like it better this way? Yes.

:lipstick: :mortar_board: Topic20 Change how recursive binary search parameter values are passed

---

.gitignore
src/site/lab3.rst
src/site/lab7.rst
src/site/topic15.rst
src/site/topic17.rst
src/site/topic18.rst
src/site/topic22.rst
src/site/topic4.rst
src/site/topic5.rst
src/site/topic6.rst

I was bored this morning waiting for deployments, so I opted to resolve some sphinx warnings to kill time.
Also adding `_build` and `.vscode` to gitignore. Not sure why `_build` wasn't there (maybe my sphinx was weird?), and `.vscode` since that was what I used to do this.
Some pages had rendering issues, others were just sphinx being confused but mostly doing the right thing.
IDEs are good at underlining warnings. I use them. In IDE preview was what I was using to render.
`./gradlew clean site`
There are still some warnings.
```
/snip/git/cs102/src/site/topic18.rst:38: WARNING: Bullet list ends without a blank line; unexpected unindent.
/snip/git/cs102/src/site/topic19.rst:189: WARNING: Definition list ends without a blank line; unexpected unindent. …
```

:bug: :lipstick: fix a bunch of sphinx warnings

---

src/site/topic23.rst

Increase the size of the adding example image.
Too small. 
It was set to 250px, but I made it 666px since I think it will match the image above it better.

:art: Topic23 Resize image for the example of adding

---

src/site/topic14-careful.rst
src/site/topic14.rst

Resize some images in topic 14 so they are more appropriately sized. The square and rectangle in the aside are also sized based on height so it will be easier to get a matching size for the shapes. 
Some were too big, others too small. Ultimately, better viewing. 
The collections heirarchy image was too small
The joke image about inheritance in the aside was also too small
The Square was stupidly large
Rectangle was also too large

:art::lipstick: Topic14 Resize various images

---

src/site/topic2.rst

Change the `*` -> `&` in a comment
It should have been &. Must've fat fingered it. 
Comment showing how we can declare and then assign the values later in Java

:bug: Topic2 Fix wrong character in comment

---

src/site/topic2.rst

Remove "each" from the for loop comment
Previous example was the _for each_ example, this example is the counting for loop
Counting for loop example. 
Will also be fixed in aside with C++ added.

:bug: Topic2 Fix for loop comment

---

src/site/lab3.rst

Fix the link to lab2. 
It was broken
`` `:doc: Lab2 </lab2>` `` -> ``:doc:`Lab2 </lab2>` ``

:bug: Lab3 Fix link to lab2

---

src/site/topic23.rst

Closes #377 
Add a download link for the linked binary search tree tests to the bottom of the page.
It was missing.
The end of the topic, where the download links usually are.

:bug::mortar_board:  Topic23 Add download link to tests

---

src/site/lab1.rst
src/site/lab4.rst
src/site/lab5.rst
src/site/lab8.rst

Same idea as #123 
Remove the line numbers from the code blocks in the lab for easy copy/paste. Line numbers are great in general, but not when they are specifically told to copy/paste. 
When copying and pasting with the line numbers, it will compy the line numbers at the beginning of each line, which is a pain. 
A bunch of the labs. 
ctrl-f :linenos:

:lipstick: Labs Remove numbers from lab code

---

src/site/topic2.rst

Remove the warning about Cpp at the top of topic2. 
It should not have been there. 
Topic of Topic2
Build local
I think I remember wondering why a warning was not in the Cpp aside originally, so I added it there, so I'm betting I had originally had it hin the wrong spot.

🐛 Topic2 Remove cpp warning

---

src/site/topic9.rst

Space out the math so the **growth function** and **order** are on different lines
Looks better, and it was intended to be like this in the first place
Replace this text with a detailed description of where the change is/should be and why (should it be an aside?). 
If the where is obvious because of _Files changed_, then you don't fill this in. 
ctrl-f
enter
build local

:lipstick::bug: Topic9 Add extra lines for math formatting

---

src/site/asn1.rst

Removing something from #407 
Remove the `equals` method from the `Country` class
Ended up changing the assignment such that this is not needed. 
Built local 
The assignment is changed slightly to streamline some of the requirements.

:bomb: Asn1 Remove Equals Method from Country

---

src/site/asn1.rst

As discussed in #414 
Put the `equals` method back into the `Country` class, and add the `hashCode` method into the class and assignment description. 
Needed to make the map work for the `CountryCatalogue`
Built local

:mortar_board: :bug: Asn1 Put `equals` back and add `hashCode`

---

src/site/asn1.rst

Follows #414 
Add more questions/functionality for/to the class
This will follow the first half of questions in #414. Note the numbering will start at `1` in this series of questions as a consequence of using `#`. Once combined with #414, the numbering will be correct. 
Built local
1. I was not a huge fan of the spacing for the `CountryCatalogue`'s `toString` example. I tried to make it a code block, but then it started emphazising things weird, so I stuck with the verbatum/codelike text. 
2. I originally wanted to have ``filterCountriesByContinent`` return a new ``CountryCatalogue``, but thought that perhaps that would be a _little much_ at this stage --- "wait, objects can create instances of themselves? :exploding_head:" Changing this to be a new ``CountryCatalogue`` would almost be …

:mortar_board: Asn1 `CountryCatalogue` Second Half

---

src/site/asn1.rst

After a realization from #418 
Remove the `equals` and `hashCode` methods from the `Country` class
Remove the map field from the `CountryCatalogue`
Add a note about maps for `findMostPopulousContinent` since it makes life easy
None of it is needed and it simplifies stuff
Built local

:bomb: Asn1 Remove `equals`, `hashCode` and map stuff from `CountryCatalogue`

---

src/site/topic3.rst

Closes #433 
Remove the `capacity` field from the `ContactList` discussion in topic3
Not needed. This was an artifact of copy/paste from cpp.
Also snuck in a fix `expand capacity` -> `expandCapacity` in topic.

:bug: 🔭 Topic3 Remove Capacity

---

src/site/asn1.rst

Add a note that scientific notation is fine for the strings of the floats 
It'll happen to them, and worrying about string formatting is not the point. 
The toStrings
Just a point about it being fine.

🆕 Asn1 Scientific Notation Note

---

src/site/topic3.rst

Add a warning about the bug in the `remove` method. Mention that this issue is discussed below. 
It's a bug. It gets addressed later, but now more directly to eliminate confusion. 
Under `remove` and `indexOf`

:new::bug: Topic3 Note the bug in remove

---

src/site/data/Assignment2/src/DfsMazeSolver.java

As discussed in #466 
Include an empty `solve` method in the `DfsMazeSolver`.
1. It will eliminate the error of not implementing the `MazeSolver` interface. 
2. It will make part 2 of the assignment a little easier. 
3.
I checked, and this does not create inconsistencies in the asn2.rst file

:new: Asn2 Include empty `solve` in `DfsMazeSolver`

---

src/test/java/ArrayStackEqualsTest.java

Throw in the capacity for `gTypeCapacity`
It should've been there. 
Will update in the other repo too.

:bug: `ArrayStackEqualsTest` Include Missing Capacity

---

src/site/topic11.rst
src/site/topic12.rst
src/site/topic6.rst
src/site/topic8.rst

Add download links to the thorough versions of the tests for the stacks and queues. 
For their reference. I like the idea of keeping the simpler ones in as a starting point for them. 
End of each topic's respective page. Note that the `ArrayStack` had no download to the tests originally since it was included in the aside, but I opted to add download links to the main page too.

🆕 Add Download Links to the Thorough Tests

---

src/site/asn2.rst

Add a warning about needing to add JUnit. 
Some students are finding that they still need to tell IntelliJ to add JUnit for them.

🆕 Asn2 Add warning about adding JUnit

---

src/site/asn2.rst

`MazeRenderer` -> `MazeRendererTest`
It's wrong
This was addressed for asn3 already in #491

:bug: Asn2 Fix Renfererererer test class name

---

src/site/data/Assignment4/test/HuffInternalTest.java
src/site/data/Assignment4/test/HuffLeafTest.java
src/site/data/Assignment4/test/HuffNodeComparatorTest.java
src/site/data/Assignment4/test/HuffmanCodeTest.java

- Put the complete `HuffNodeComparatorTest` back
- Put the methods back in all other test classes, but leave them empty
Since the comparator is a huge integral part of the assignment, I figure this will help a lot. 
I think having them do them all on their own is a bit of a jump. Depending on how this year goes, this may change. Having the skeleton of the methods should help a lot while still having them think about them.

🆕 Asn4 Add Test Details Back

---

src/site/lab5.rst

Closes #523 
Make the method creating the structure not generic. 
It ends up just confusing them because the way it is requires them to cast it as `T`, which is weird. 
Wasn't planning on fixing it now, but whatevz.

💄 Lab 5 Change `T` -> `Integer` in first method

---

src/site/index.rst

Add asn4 to the index page. 
So people can get to the page easy.

🎓 Asn4 Add Link to index

---

src/site/topic12.rst

FIx the typesetting so the `code like stuff` renders properly. 
It was busted --- missing a close \`\`

:bug: Topic12 Fix Typesetting

---

src/site/topic12-expand.rst

Closes #153 
Reorder and massage the content in the aside to introduce the simpler `arrayStack` `expandCapacity` that they are already used to. 
As @twentylemon suggests in #156, it's probably better to start with what they know, not the other way around.

:lipstick: Topic12 `expandCapacity` Aside Reorder

---

src/main/java/PlayingLinkedStack.java
src/site/topic8.rst

Related to #77 
Related to #479
Make the playing code downloadable. Also make use of `:literalinclude:` 
- It's better to just be able to download it. 
- `literalinclude` will defo help with consistency going forward
Built local
I added line numbers back in. Originally they were cut to make for easy copy/paste, but I like being able to reference line numbers when talking about stuff.

💄 Topic8 Playing Code Download

---

src/test/java/LinkedQueueThoroughTest.java

Rename test method to use queue instead of stack
Because it's a queue, not a stack.

🐛 Stack -> Queue

---

src/site/cpp-pointers.rst

- Replace the tab with spaces so it formats correctly
- Make images bigger to be viewable
- ~Remove "sorting" from reference since these ain't sorting images.~
- Remove reference to images from wiki because they not from wiki

🐛 Cpp Pointers Fix Typesetting

---

src/site/topic16.rst

change "For example, here is an example of using an iterator to iterate over an arbitrary iterable thing of type ``T``" to "For instance, here is an example of using an iterator to iterate over an arbitrary iterable thing of type ``T``"
:new: :bomb: :mortar_board: :memo: :robot: :lipstick: :bug: :telescope: :art: Add relevant emojis to title. [See style guide.](https://github.com/jameshughes89/cs102/blob/main/CONTRIBUTING.md#style-guidelines).
If applicable, replace this text with links to issues and other PRs. [Link with a keyword if you can.](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue)
Typo in topic16 changing "For example, here is an example" to "For instance, here is an example"
Because grammar is a nice thing
In …

🐛 : typo in Topic16 (Example to Instance)

---

src/site/cpp-references.rst

Remove an extra space between `a` and `b`
I expected more changes, but I guess this is it.

:bug::poop: Cpp Reference Remove extra space

---

src/main/java/LinkedIterator.java

Make the `current` node be a private field
Should have been in the first place. 
Yep.

💄 LinkedIterator Make Field Private

---

src/site/cpp-arrays.rst

Move the point to the sentence. 
It will look better this way. 
It was a point because I mentioned this and `std::array`` too. Now the arrays are not mentioned.

:lipstick: Cpp Arrays Note Move Point to Sentence

---

src/site/asn3.rst

Issue 573
Change Assignment 3, Part 3, Implementing the class, "T front()" to "T first()"
In the Queue interface provided for the assignment, T first() is the method required as per the interface, but the assignment description asks for T front()
In Assignment 3 description for implementing LinkedPriorityQueue
Changing T front() to T first()

Update Method Name

---

src/site/asn4.rst

Move due date back to the last day possible. 
Because I'm nice. 
I also expected to be a _liiiiiitle_ further in the course content. There's no reason they are not able to do it by Monday as is, but this will help nonetheless. 
1. The exam will be released the same day at like noon-ish (whatever the uni's date/time is). 
2. The 7 day no penalty will still apply, but will be overwhelmingly discouraged.

🎓 Asn4 Update Due Date

---

src/site/cpp-syntax.rst

"And" seems to be misspelled as "end"
Spelling mistake
C++ Lessons #1, just above "Variables and Types" header

"end" -> "and" spelling mistake

---

src/site/cpp-syntax.rst

"that that" is changed to "from that" and "kinda' " is changed to "kinda" (no apostrophe)
incorrect otherwise
C++ Lessons #1, under "Variables and Types" header
replace first "that" with "from" or other suitable replacement, and hit backspace on apostrophe attached to "kinda"

double "that" -> "from that" and misplaced apostrophe

---

build.gradle
src/site/_static/css/custom.css
src/site/conf.py
src/site/index.rst
src/site/outline/outline.rst

1. Change the theme to the rtd theme (the one cs101 uses)
2. Change the order of the contents in index
3. Make use of "caption" so the side bar looks nicer
Looks nicer and consistency
Copy from cs101. 
built local, looks good. 
1. Originally the abc theme was used since it kinda' sortof kinda reminded me of the javadocs, but really, that was a stretch
2. The abc theme is yuck
3. I do *not* like that the colours of the theme are the same as cs101. This could end up being confusing to students. In a future PR the colour theme will change to be like red or something, or maybe a nice coffee brown. 
4. The RTD theme has it so anything with subpoints becomes boldfaced. I do not like this. This will require going over the contents of the course to add white space. This is fine since (a) I need …

:lipstick: Course layout --- Change to RTD theme

---

src/main/java/ArrayStack.java
src/main/java/LinkedStack.java
src/main/java/Stack.java

Clean up the javadoc comments within the stack interface. 
It's a little better now. 
I'm going to try to be consistent going forward with wording (e.g., element vs. item).
`ArrayStack` and `LinkedStack` have been updated to just make them shut up since `push` returns a boolean now. These classes will be updated in some subsequent PR along with their tests.

:technologist: Stack Interface --- Clean up comments

---

src/main/java/ContactList.java
src/site/topics/objects-review/builder.rst

1. Clean the string builder aside
2. Remove the use of `toString` in the string builder of the `ContactList` class. 
1. General yearly clean up
2. The main contend does appending to the string. The aside is to show them the builder. Although the `toString` may be more clear to the first time they see it, they _should_ be seeing it for the first time in the aside. Thus, the actual code will not be the first time they see it. 
:+1: --- removing `toString `did not kill any tests.

💄 StringBuilder Aside --- Clean 🧹 

---

src/main/java/Stack.java

From #641
Reword `@throws` line to not include "throws" 
It does sound better. 
I went with the "throws" in the line because I looked up an example of how people wrote the line. They had it, so I added it. Regardless though, it does read weird; removing "throws" is superior.

💣 Stack Interface --- Remove "throws" from @throws line 🔬 

---

build.gradle
src/test/java/ContactListTest.java

~Change the contains test to check for a friend that is not the beginning.~
Change the many tests to check an existing friend at the start, middle, and end
~It was checking the first one. Singleton tested first one. Now it's another one that happens to not be the first one.~
~It'll also be more similar to the index of and get tests for many.~
It's better this way
Parameterized test
:+1:
~Although some of the parameterized tests did not use both arguments (the int index one), I included it in the test method parameter list so I didn't get confused in the future about how the stuff was actually passed to the method.~
There are two method sources. One with indices, one without.

🧑‍💻 ContactListTest class --- Improve many tests to do first, middle, and end

---

src/test/java/LinkedStackThoroughTest.java

Will fix the issue in #653 
Change the stack being tested to a linked stack
It's currently an array stack being tested in the linked stack test, which is silly. 
:+1: 
This is *not* a clean up of the linked stack stuff. It is simply fixing a bug.

:bug: Linked Stack Tests --- `ArrayStack` -> `LinkedStack` :microscope: 

---

src/main/java/ArrayQueue.java
src/main/java/LinkedQueue.java
src/main/java/Queue.java
src/test/java/ArrayQueueTest.java
src/test/java/ArrayQueueThoroughTest.java
src/test/java/LinkedQueueTest.java
src/test/java/LinkedQueueThoroughTest.java

Clean up the queue interface. Biggest change is to have enqueue return a boolean (thus, the implementations had a `return true` added to the end of their enqueues. 
General yearly clean. Also makes more consistent with the wording of the stack interface. 
Replace this text with a detailed description of how it is addressed.
:+1: just in case.

💄 🧑‍💻 Queue interface --- Cleanup 🧹 

---

src/site/topics/stacks/array-stack.rst

Remove the reference to the builder aside.
The builder aside was incorporated into the main topic. 
Odd that I missed it before as I check for these.

:bug: :mortar_board: Array stack topic --- Remove link to removed aside :microscope: 

---

src/main/java/ArrayQueue.java
src/main/java/ArrayStack.java
src/main/java/LinkedQueue.java
src/main/java/LinkedStack.java
src/main/java/PlayingArrayStack.java
src/main/java/PlayingLinkedStack.java
src/main/java/Queue.java
src/main/java/Stack.java
src/site/topics/stacks/array-stack.rst
src/site/topics/stacks/linked-stack.rst
src/test/java/ArrayQueueTest.java
src/test/java/ArrayStackTest.java
src/test/java/LinkedQueueTest.java
src/test/java/LinkedStackTest.java

#685 
Stop using the `EmptyCollectionException` 
It's not a standard exception. I figure it's better to go with something that Java already gives you. 
1. Stack stuff (interface, implementations, tests, playing code)
2. Stack topic (needed to update the line numbers in the literal includes
3. Queue stuff (interface, implementations, tests)
Switched out to a `NoSuchElementException` with a message `Empty stack`/`Empty queue`. I looked for a relevant exception that was just in Java lang, but for better or worse, `NoSuchElementException` seemed to make the most sense. Annoyingly, this meant I needed an import, which threw off the line numbers in the topic code. 
:+1:
- Built local, looks good
- Ran unit tests, looks good. 
- Ran playing code, looks good. 
There is still reference to an …

💄 Remove the use of `EmptyCollectionException` 

---

src/main/java/ArrayQueue.java
src/main/java/ArrayStack.java
src/main/java/ContactList.java

Change the name of the capacity param in the constructors for the array based collections to be `initialCapacity`. As @twentylemon pointed out in the other repo, this is more consistent with the standard library. 
Consistency
:+1:

:telescope: :technologist: Array based collections --- `initialCapacity` :microscope: 

---

src/site/topics/bags/bag-implementations.rst

Fix the ordering of the elements in the `compareTo` explanation. 
It was backwards. :grimacing: 
Yes, to be sure I wasn't crazy:
```java
Integer x = Integer.valueOf(1);
Integer y = Integer.valueOf(2);
System.out.println(x.compareTo(y));
```
resulted in `-1`
This is not part of the cleanup. I just happened to notice so I figured I would fix this ASAP.

:bug: :mortar_board: Bag Implementation Topic --- Fix `compareTo` ordering details :microscope: 

---

src/site/index.rst

Hide the labs until they are ready. Lab 1 is left since #694 exists. 
There may be some less than insignificant changes. This way there is no potential for confusion if students go ahead.

💣 🎓 Labs --- Hide labs

---

src/site/topics/java-vs-python/java-vs-python.rst

1. Change the java example of a method to use convention and have semicolon 
2. Change some warnings to notes
1. It was wrong
2. The changed ones feel more like notes than warnings

:bug: :lipstick: Java vs. Python topic --- Fix java example and change warnings to notes

---

src/site/assignments/country-catalogue/country-catalogue.rst

Clean up the details on the country catalogue class. 
A lot of it was based on the description in 161, but details are deliberately cut down where possible. At this stage I expect them to fill in some blanks. Unlike previous years, I am removing explicit mention of private methods as they should be able to figure them out if they feel they need them. Besides, things like `find` returning a sentinel value is covered in lecture topics and labs. 
There is mention of the `NOT_FOUND` constant which I considered removing, but I've left it since it may serve as a hint that something like a private `find` could be helpful. Maybe that's silly, idk.

:lipstick: :mortar_board: Assignment 1 --- Clean country catalogue description bit 

---

src/site/topics/java-vs-python/java-vs-python.rst

changed the convention for the java code on line 560 from snakecase to camelcase.

:bug: typo fix for pretend code

---

src/test/java/ArrayStackTest.java

Remove the tests for push resulting in a new top
They're useless 
:+1:
I'm not sure why they were there to begin with. I looked at #653 to see if there was an explanation, but there was not. Either way, _if_ the intention was that they were there to point at to explain that they are unnecessary/redundant, this is being explicitly hit in the relevant course topic now.

:bomb: :technologist: `ArrayStackTest` --- Remove useless tests

---

src/test/java/ArrayQueueTest.java

Similar to #720 
Remove the tests on enqueue resulting in a new or unchanged first
They're uselesss as this gets tested indirectly 
- push empty new top (which is a typo anyways since it should be `first`, not `top`) is tested with the singleton test on peek
- push singleton unchanged is tested with the many test on peek 
:+1:

:bomb: :technologist: `ArrayQueueTests` --- Remove useless tests

---

src/site/index.rst
src/site/topics/testing/unit-test-collections.rst

Add the details on the more general "`test`" cases.
There was an issue with the many tostring test having a bad name. A subsequent PR to fix this in the code will be made. 
This section was easy to make since it's more-or-less a follow through of the previous topics.

:new: :mortar_board: Unit Testing Collections Topic --- Many tests

---

src/site/topics/java-vs-python/java-vs-python.rst

1. Add a new line between the one point and subpoint
2. Change how the 0 -- 9 is typeset
1. Without the newline, the _read the docs theme_ makes the parent point boldfaced. I do not like this. 
2. Idk, I just like it slightly better. 

💄🎓  Java vs Python --- Fix typesetting 🔬 

---

src/test/java/ArrayIndexedBagTest.java
src/test/java/ArrayQueueTest.java
src/test/java/ArraySortedBagTest.java
src/test/java/LinkedQueueTest.java
src/test/java/LinkedStackTest.java

Same as #723 but for the remaining tests. 
1. Change `toString_singleton_returnsCorrectString` -> `toString_many_returnsCorrectString`
2. The bags had iterator tests with the same issue as 1
3. Change `Y_successfullyAdds_returnsTrue` -> `Y_X_returnsTrue` where `X` is the empty, singleton, or many and `Y` is the way to add (not relevant for indexed bag)
1 & 2. They were many test with bad names
3 Although the nested classes will make it clear if the test is for an empty, singleton, etc. type test, this is a little clearer. And, really, "successfullyAdds" is not really helpful since, based on the way the actual methods are done, there really isn't a way to not successfully add anyways, so something like "successfullyAdds" is meh. Finally, this will make the code consistent with how the …

:lipstick: :bug: :technologist: Other Stack, Queues, and Bags --- Change test names

---

src/test/java/ArrayStackTest.java

Brought up in #722 
1. Change `toString_singleton_returnsCorrectString` -> `toString_many_returnsCorrectString`
2. Change `push_successfullyAdds_returnsTrue` -> `push_X_returnsTrue` where `X` is the empty, singleton, or many
1. It was a many test with a bad name
2. Although the nested classes will make it clear if the test is for an empty, singleton, etc. type test, this is a little clearer. And, really, "successfullyAdds" is not really helpful since, based on the way the actual methods are done, there really isn't a way to not successfully add anyways, so something like "successfullyAdds" is meh. Finally, this will make the code consistent with how the tests were presented in the relevant topic. Since the tests started without nested classes, something like "empty" in the test name was …

:bug: :lipstick: :technologist:  `ArrayStackTest` --- Change test names

---

src/site/topics/stacks/stack-adt.rst

Remove the space between the word `Stack` and `<T>`. 
Consistency 
yolo

:lipstick: :mortar_board: Stack Topic --- Remove space in interface :microscope: 

---

src/main/java/BinaryNode.java

Small update to #730 
Alter the class doc to not explicitly say "`BinaryNode`". 
Since this is actually supposed to be an internal class in the `LinkedBinarySearchTree` class called `Node`, it would be lame if the copy/paste from this class to the internal class had to be changed.
Just called it a "binary node" once, and then node everywhere else in the doc. 
Obviously there will need to be some change to the class when copy/pasted since it's actual name is changed (`BinaryNode` -> `Node`). But, removing the need for extra changes is nice.

:lipstick: :technologist: `BinaryNode` --- Update class doc a little more

---

src/site/assignments/country-catalogue/country-catalogue.rst

Add a warning next to the first mention of running unit tests about using JUnit 5, not JUnit 4. 
Using JUnit 4 will make the tests, as written, not work. 
Just warn. 
Originally I had details on how to remove the JUnit 4 stuff from the project .iml file, but I figured that's likely to cause more issues. 
The warning, because it is indented under the point, does seem a little smushed next to the previous point, but to me it makes the warning more obvious that it is attached to the specific part of the assignment. 
Indented
Not indented

:new: :mortar_board: Country Catalogue Assignment --- Warn about JUnit 4

---

src/site/topics/objects-review/objects-review.rst

1. Say "above" instead of "below"
2. Explain that one can actually screw up with the way the `Friend` class is written
1. It's above, not below (was below when it was in the aside) 
2. It was wrong

:bug: :mortar_board: Objects Review --- Fix note on null safe equals

---

src/site/topics/stacks/stack-adt.rst

6x6 -> 6x7
The maze is 6x7 not 6x6
:-1: YOLO 
Is there a convention? Should it be 6x7 or 7x6? 6x7 _sounds_ better to me, but idk why.

:bug: :mortar_board: Stack ADT Topic --- Fix maze dimension :microscope: 

---

src/test/java/ArrayIndexedBagTest.java
src/test/java/ArrayQueueTest.java
src/test/java/ArraySortedBagTest.java
src/test/java/LinkedQueueTest.java

Redo of #766 
Rename `@BeforeEach` tests for queue and bag tests 
They included "stack" when they had nothing to do with stacks. 
:+1:
Caused by lazy copy/paste I assume

:bug: :technologist: Unit Tests --- Rename setup tests :microscope: 

---

src/site/topics/queues/array-queue.rst

Remove the warning about understanding expand capacity
Feels silly to warn about learning something I told them to learn. Also, there is an aside that goes into more detail.

:bomb: :mortar_board: Array Queue Topic --- Remove expand capacity warning

---

src/site/topics/queues/array-queue.rst

Change out the word loop/looped to wrap/wrapped 
Although _loop_ works fine, I feel like it's better to not use the word _loop_ when the content could easily be also talking about literal loops.

💄 🎓 Array Stack Topic --- Change "looped" to "wrapped" 🔬 

---

src/main/java/ArrayQueue.java
src/main/java/ArrayStack.java
src/main/java/ContactList.java
src/main/java/LinkedQueue.java

#169
Change `top`/`rear`/`size` to the method call `size()` where it makes _sense_. 
1. Consistency
2. Improve quality of code --- do we care about `size()` here or the arbitrary field?
I tried to make use of `size()` where it makes sense. For example, are we looping to `rear` or `size()`? Both are correct, but `size()` is clearer in the context. For another example, are we hashing the value of `size()` or the value of the field that happens to represent the size? Again, both are correct, but it's not _size_ that matters, but the value of the field that's hashed. 
This does get weird though, because, 
```java
private void shiftLeft(int start) {
for (int i = start; i < rear - 1; i++) {
bag[i] = bag[i + 1];
}
bag[rear - 1] = null;
}
```
why not change `rear` to `size()`? That would be …

:lipstick: :woman_technologist: Use `size()` where it makes sense

---

src/site/topics/stacks/stack-adt.rst

Remove the :.java" from the download link
1. I don't like it
2. It is not typically used throughout the course

:telescope: :mortar_board: Stack ADT Topic --- Remove ".java" from download link

---

src/site/topics/stacks/stack-adt.rst

Remove the use of `public` in the interface examples in generics 
Not needed, and it was explicitly said to not include `public`in the earlier example

:telescope: :mortar_board: Stack ADT Topic --- Remove `public` from interface examples

---

src/site/topics/testing/unit-test-collections.rst

1. Add the missing `push` on `preState` in the one test
2. Fix the name of the singleton test to not say "empty"

:bug: :mortar_board: Unit testing collections topic --- Add missing call and fix typos 

---

src/site/topics/queues/linked-queue.rst

Change Queue -> queue in the first line in the intro 
it shouldn't start with an upper case here, unless it was `Queue`, which it _could_ be, but it's really not talking specifically about the interface.

:lipstick: :mortar_board: Linked queue topic --- Queue -> queue :microscope: 

---

src/main/java/SearchingFunctions.java
src/main/java/SearchingMethods.java
src/site/topics/searching/searching.rst
src/test/java/SearchingFunctionsTest.java
src/test/java/SearchingMethodsTest.java

Clean up the code and tests
:+1:
1. The type mismatch tests were inadmissible for the binary search.
2. I abused the `recursiveBinarySearch` call for the `null` tests by passing arguments to suggest there was a size. 
3. I opted to add a `NOT_FOUND` constant to the test class as I still think it was nicer than just `-1`.
4. I _could_ change the binary search methods to behave the same way as the linear with a `null` needle, but idk, meh.

:lipstick: :technologist: `SearchingMethods` --- Clean :broom: 

---

src/site/assignments/country-catalogue/country-catalogue.rst

Add a space between the verbatim `area` and the word "of" 
Fixes the typesetting.

:bug: :mortar_board: Country Catalogue Assignment --- Fix typesetting (missing space) :microscope: 

---

src/site/outline/outline.rst

Add the date for test 2 to the outline. 
Date is the start of week 9 of the semester. This means it's 2/3rds of the way through. This works nice. Test 1 was 1/3rd.

:new: :mortar_board: Test 2 --- Add date to outline :microscope: 

---

src/site/topics/iterators/iterators.rst

Closes #693
Show how to use iterators to improve equals such that equality can be checked between implementations 
- :+1: built locak, looks good
- :+1: implemented the shown `equals` to test correctness, and it worked. 
I'm going with "closes" #693 since it can get hairy going back and changing the actual implementations in the code. This aligns with @twentylemon's suggestion:
> An alternative is they can be broken. The introduction of iterators later could frame a reimplantation of equals to further drive reasoning for interfaces. Objects are their interfaces first and foremost, not their implementations -- at least to users of the object.

:new: :mortar_board: Iterator topic --- Show updated stack `equals`

---

src/main/java/ArrayIndexedBag.java
src/main/java/ArraySortedBag.java

- Change `equals` in `ArrayIndexedBag` to use iterator
- Change `hashCode` in `ArrayIndexedBag` to use iterator
- Change `equals` in `ArraySortedBag` to use iterator
- Change `hashCode` in `ArraySortedBag` to use iterator
:+1: 
This change does not impact any `literalinclude` in the topics

:lipstick: :technologist: Bag Implementations --- Change `equals` and `hashCode` to use iterators

---

src/test/java/ArraySortedBagTest.java

Add unit tests for checking if the collection is unchanged when calling first & last
They're missing. Feels like they should be checked since they are the alternative to `removeFirst` and `removeLast`. 
:+1:
There is no similar change to the indexed bag tests since there isn't a similar thing to first & last. The most similar would be `get`, but, idk, feels like checking unchanged on that isn't really necessary when compared to this since `removeFirst` explicitly removes the first and returns it and `first` is just returning it, so it's important to check that it's not changed.

:new: :technologist: `ArraySortedBagTest` --- Add tests for first and last leaving collection unchanged

---

src/test/java/LinkedBinarySearchTreeTest.java

Add unit tests for checking counts and remove with duplicates. 
Only checked `remove` resulting in removing one element via counts. Did NOT check if it removed a "first". Also checked the counts worked with duplicates. 
I _was_ going to include tests for remove min and max with duplicates, but then realized that removing min and max where they could be duplicate values is really not a special case. 
:+1:

:new: :technologist: `LinkedBinarySearchTreeTest` --- Duplicate tests

---

src/main/java/ArraySortedBag.java

Have the index in the array set to null when removing last 
Mostly consistency. All other cases in the class would set the removed element's old index to null. Further, the data is not supposed to be there anymore anyways, so might as well yeet it.  
:+1:
Someone spotted it in lab and asked about it.

:telescope: :technologist: `ArraySortedBag` --- Set "empty" array index to null after `removeLast` :telescope: 

---

src/site/topics/bags/bag-implementations.rst

Mention that `indexOf` may throw an exception if the element does not exist. 
The `indexOf` method is not discussed in the course notes, and although it is mentioned in a comment, having it spelled out is good. Someone asked about it during lecture today. 
This _could_ be addressed by explicitly talking about `indexOf` in the notes, but (a) it has been discussed before earlier in the semester, and (b) it would require talking about `contains` and then `find` and then iterators since the `find` uses iterators. This is ideally avoided here since iterators are discussed in the subsequent topic.

:mortar_board: Bag Implementations Topic --- Note that `indexOf` may throw an exception

---

src/site/topics/iterators/iterators.rst

Fix the more general stack equality check example
`this.getClass() != other.getClass()` -> `other instanceof Stack` 
There's a bug --- it doesn't check if the type is a Stack. Instead it checked if they were the same class. 

:bug: :mortar_board: Iterator Topic --- Fix error in equals

---

src/site/topics/trees/tree-adt.rst

Say that it's the HEIGHT of the tree that is zero
It doesn't say height and reads weird.

:bug: :mortar_board: Trees ADT Topic --- Mention height :microscope: 

---

src/main/java/LinkedBinarySearchTree.java

Update the exception message to just say the element that was being looked for 
It said "empty tree" which wasn't the best message. Someone could argue that _technically_ it's a correct message in that the subtree is empty, but still, the message is better this way. 
Make it return the string of the element being looked for like the other data structures. 
:+1:
Noticed during lecture.

:bug: :technologist: Linked Binary Search Tree --- Fix general remove exception for non exist item

---

src/main/java/LinkedBinarySearchTree.java
src/site/topics/trees/linked-binary-search-trees.rst

- Stop saving the element from the node being removed 
- Update the line numbers in the course content 
- It's not returned. 
- They are wrong due to code changes
- :+1:
- :+1: built local, looks good 
I'm guessing it exists from the previous version that returned the element that was returned --- vestigial.

:lipstick: :technologist: :mortar_board: Linked Binary Search Tree --- Remove useless variable

---

src/site/assignments/country-catalogue/Assignment1/test/CountryCatalogueTest.java
src/site/assignments/country-catalogue/country-catalogue.rst

#899 
Also the PR in the private repo 
Change the assignment such that removing an element that does not exist now returns `false` instead of throwing an exception
- Update the unit tests
- Update the assignment description
More consistent with java collections 
This is jumping the gun as the PR in the private repo is yet to be approved. This PR will not be merged until the corresponding private repo one is merged.

:mortar_board: :technologist: Country Catalogue --- Remove returns `false`

---

src/main/java/BinarySearchTree.java
src/main/java/BinaryTree.java
src/main/java/LinkedBinarySearchTree.java
src/site/topics/trees/linked-binary-search-trees.rst
src/test/java/LinkedBinarySearchTreeTest.java

#899 (this should be the last of them related to this one) 
Make it such that removing a non-existing element from a tree has the method return false instead of throwing an exception. 
Consistency with java collections 
Similar to #938 and the exceptions being thrown if the tree is empty in the other remove methods. 
I originally kept the exception thrown in the private `remove` method if the current node is ever null, which was originally what was propagated up to the public remove if the element did not exist. I thought it may make the code more clear for the students to check that case, but upon further thought, I think it may be more confusing to keep if it's kinda' useless. 
:+1:

:mortar_board: :technologist: :lipstick: Trees --- Remove method returns `false` 

---

src/main/java/ArrayIndexedBag.java
src/main/java/ArraySortedBag.java
src/main/java/Bag.java
src/main/java/SortedBag.java
src/site/topics/bags/bag-implementations.rst
src/test/java/ArrayIndexedBagTest.java
src/test/java/ArraySortedBagTest.java

#899 
Have it such that the bag implementations return `false` when the element does not exist within the bag. 
Consistency with java collections 
This one has a little more nuance since before the remove could throw two exceptions: one for when the bag was empty and one for when the element did not exist. I opted to just return false in both cases. This made the method slightly simpler too. 
This got kinda' weird though since, for example, in the sorted bag, exceptions are still thrown if the bag is empty when calling remove first/last. My justification for this is, the general remove returns a boolean, so the boolean tells us what we need to know on the success/fail of the method call. For the remove first/last, they return an actual element, so the exception still makes sense here …

:mortar_board: :technologist: :lipstick:  Bag implementations --- Remove method returns `false`

---

src/main/java/LinkedBinarySearchTree.java

#480
Update the hashCode method such that it always multiples the current hash by a prime before addinng a new elements hash
Better this way 
:+1: 
Currently the only unchanged ones (RE #480) are the bag ones because they get weird as the order of the elements for an equality check does not matter. Throwing primes at the hash when looping over the collection would break things.

:lipstick: :telescope: :technologist: Linked BST --- Update hashcode 

---

src/site/topics/trees/binary-trees.rst
src/site/topics/trees/tree-adt.rst

~Part of~
Closes #621
Remove all uses of rst `image::` and replacve with `figure`
Figure is better
:+1: 
There were only 2 I had missed from last year. Found them with grep.

:lipstick: Figures --- Use `figure` instead of `image` :microscope: 

---

src/site/topics/exceptions/exceptions.rst

Closes #943 
Update the description of the exception example. 
Shift the focus to `removeFirst` but also discuss the design decision of not having the general remove throw an exception. 
When the removes were changed to not throw an exception, it became a bad example. 
~Not yet, but will check artifact~
👍

🎓 💄   Exceptions topic --- Update `remove` exception example discussion

---

src/main/java/ArrayIndexedBag.java
src/main/java/ArrayQueue.java
src/main/java/ArraySortedBag.java
src/main/java/ArrayStack.java
src/main/java/Bag.java
src/main/java/BinaryNode.java
src/main/java/BinarySearchTree.java
src/main/java/BinaryTree.java
src/main/java/ContactList.java
src/main/java/Friend.java
src/main/java/IndexedBag.java
src/main/java/LinkedQueue.java
src/main/java/LinkedStack.java
src/main/java/Node.java
src/main/java/Queue.java
src/main/java/SortedBag.java
src/main/java/Stack.java

Closes #810 
Remove the periods in the param/return/throws lines in the javadoc comments
conforms to what I was seeing in the standard library
YOLO
It does feel weird using other punctuation, like commas, and not periods, but whatever.

🔭 💄 🎓 Javadoc comments --- Remove periods

---

src/test/java/ArrayQueueEqualsTest.java
src/test/java/ArrayStackEqualsTest.java
src/test/java/ContactListEqualsTest.java
src/test/java/LinkedQueueEqualsTest.java
src/test/java/LinkedStackEqualsTest.java

Closes #830 
1. Create `of` factory methods to create the instances of the classes to check equality on 
2. Use the factory methods when creating the instances
Much cleaner 
:+1: 
The `ArrayQueueEqualsTest` still does create a few instances without an `of` since they were peculiar and it didn't really make sense to make a method for these special cases. Specifically, the tests where the front of the queue is not at index `0` and when the queue's data loops back on the array.

:lipstick: :technologist: Equals tests --- Make use of `of` method

---

src/site/topics/queues/array-queue.rst

`4/2 == 0` -> `4/2 == 2`
Because 4 divided by 2 is 2, not 0
:-1:

:bug: :mortar_board: Topic array queue --- Correct 4/2 :microscope: 

---

src/site/topics/inheritance/inheritance.rst

1. Remove extra backtick 
2. Reorder points 
1. It didn't render correctly because of this
2. Makes more sense (seems like it was done wrong originally)

:lipstick: :mortar_board: Topic inheritance --- Clean formatting :microscope: 

---

src/site/topics/bags/bag-implementations.rst

ArrayIndexedBag -> ArraySortedBag
It's the ArraySortedBag file to download, not an ArrayIndexedBag

:bug: :mortar_board: Topic bag implementations --- Fix name of file for download :microscope: 

---

src/site/assignments/country-catalogue/country-catalogue.rst
src/site/assignments/huffman-codes/huffman-codes.rst
src/site/assignments/maze-solver-too/maze-solver-too.rst
src/site/assignments/maze-solver/maze-solver.rst
src/site/index.rst
src/site/outline/outline.rst

Set the course up for Winter 2025. Biggest thing is the outline 
Mostly updating dates and cleaning some wording, Biggest change is the course mark breakdown and the inclusion of lecture/lab activities). 
I used to do these activities before COVID and they were pretty good. The idea is that they are trivial pop-quizzes. The level of difficulty is something like, in the lecture where we learned how to create instances of nodes to chain together, they are told to create an instance of nodes and link them together (and they can look up the course content). 
They are good because
- Encourages attendance 
- they write by hand, which is nice for them because they usually only do that during tests
- Gives me an easy way to point out important content to them 
- It has them engage with important …

🎓 ⚠️ Winter 2025 --- Prep course and set outline

---

src/site/topics/testing/unit-tests.rst

Corrected a typo. 
It there... -> If there

🐛 correct typo It -> If

---

src/site/topics/trees/binary-search-trees.rst

Remind that the contains was discussed above when going over the binary search. 
The way the content is presented is a little confusing. It seems like it's the analysis of a binary search, which would belong above when showing the binary search. However, it's presented here because it's specifically mentioning the contains operation, which is under the binary search tree operations section. 
To resolve this, I make it clearer that the method's implementation would be what was discussed above.

:lipstick: :mortar_board: Topic binary search trees --- Mention that a binary search was shown above :microscope: 

---

src/site/topics/exceptions/exceptions.rst

Effectively duplicate of #1038 
Remove mention of the `remove` exception, but update the wording to say `removeFirst`
`removeFirst` throws an exception, `remove` does not, although it did in a previous version of the code from a few years back. 
YOLO
If #1038 gets updated, I will close this PR and merge that one.

🐛 👯  🎓 Topic Exceptions --- Eliminate mention of `remove` exception 🔬 
